import {
	IconAtom,
	IconBike,
	IconBolt,
	IconBook,
	IconBookmark,
	IconBox,
	IconBriefcase,
	IconBrush,
	IconBug,
	IconCalculator,
	IconCalendar,
	IconCamera,
	IconCar,
	IconChairDirector,
	IconCloud,
	IconCode,
	IconCoffee,
	IconCompass,
	IconCpu,
	IconDatabase,
	IconDeviceDesktop,
	IconDeviceGamepad2,
	IconDeviceMobile,
	IconDeviceTv,
	IconDice5,
	IconFileText,
	IconFlame,
	IconFlask,
	IconFolder,
	IconGhost,
	IconHeadphones,
	IconHeart,
	IconHome,
	IconKey,
	IconLeaf,
	IconLock,
	IconMail,
	IconMap,
	IconMessageCircle,
	IconMicrophone,
	IconMoon,
	IconMountain,
	IconMovie,
	IconMusic,
	IconNews,
	IconPackage,
	IconPalette,
	IconPaw,
	IconPhoto,
	IconPlane,
	IconPuzzle,
	IconRadio,
	IconRobot,
	IconRocket,
	IconSchool,
	IconServer,
	IconShield,
	IconShoppingCart,
	IconStack2,
	IconStar,
	IconSun,
	IconSwords,
	IconTarget,
	IconTelescope,
	IconTerminal2,
	IconTool,
	IconTrees,
	IconTrophy,
	IconUsers,
	IconVectorBezier,
	IconVideo,
	IconWallet,
	IconWifi,
	IconWorld,
	type Icon
} from '@tabler/icons-svelte';

export const curatedIcons: { name: string; icon: Icon }[] = [
	{ name: 'device-gamepad-2', icon: IconDeviceGamepad2 },
	{ name: 'music', icon: IconMusic },
	{ name: 'video', icon: IconVideo },
	{ name: 'camera', icon: IconCamera },
	{ name: 'palette', icon: IconPalette },
	{ name: 'code', icon: IconCode },
	{ name: 'terminal-2', icon: IconTerminal2 },
	{ name: 'tool', icon: IconTool },
	{ name: 'book', icon: IconBook },
	{ name: 'school', icon: IconSchool },
	{ name: 'briefcase', icon: IconBriefcase },
	{ name: 'calculator', icon: IconCalculator },
	{ name: 'calendar', icon: IconCalendar },
	{ name: 'mail', icon: IconMail },
	{ name: 'message-circle', icon: IconMessageCircle },
	{ name: 'users', icon: IconUsers },
	{ name: 'heart', icon: IconHeart },
	{ name: 'star', icon: IconStar },
	{ name: 'bookmark', icon: IconBookmark },
	{ name: 'folder', icon: IconFolder },
	{ name: 'file-text', icon: IconFileText },
	{ name: 'photo', icon: IconPhoto },
	{ name: 'movie', icon: IconMovie },
	{ name: 'headphones', icon: IconHeadphones },
	{ name: 'microphone', icon: IconMicrophone },
	{ name: 'radio', icon: IconRadio },
	{ name: 'device-tv', icon: IconDeviceTv },
	{ name: 'device-desktop', icon: IconDeviceDesktop },
	{ name: 'device-mobile', icon: IconDeviceMobile },
	{ name: 'world', icon: IconWorld },
	{ name: 'map', icon: IconMap },
	{ name: 'compass', icon: IconCompass },
	{ name: 'rocket', icon: IconRocket },
	{ name: 'plane', icon: IconPlane },
	{ name: 'car', icon: IconCar },
	{ name: 'bike', icon: IconBike },
	{ name: 'coffee', icon: IconCoffee },
	{ name: 'shopping-cart', icon: IconShoppingCart },
	{ name: 'wallet', icon: IconWallet },
	{ name: 'shield', icon: IconShield },
	{ name: 'lock', icon: IconLock },
	{ name: 'key', icon: IconKey },
	{ name: 'cloud', icon: IconCloud },
	{ name: 'sun', icon: IconSun },
	{ name: 'moon', icon: IconMoon },
	{ name: 'bolt', icon: IconBolt },
	{ name: 'flame', icon: IconFlame },
	{ name: 'leaf', icon: IconLeaf },
	{ name: 'trees', icon: IconTrees },
	{ name: 'mountain', icon: IconMountain },
	{ name: 'home', icon: IconHome },
	{ name: 'wifi', icon: IconWifi },
	{ name: 'puzzle', icon: IconPuzzle },
	{ name: 'dice-5', icon: IconDice5 },
	{ name: 'trophy', icon: IconTrophy },
	{ name: 'target', icon: IconTarget },
	{ name: 'swords', icon: IconSwords },
	{ name: 'ghost', icon: IconGhost },
	{ name: 'paw', icon: IconPaw },
	{ name: 'bug', icon: IconBug },
	{ name: 'robot', icon: IconRobot },
	{ name: 'cpu', icon: IconCpu },
	{ name: 'database', icon: IconDatabase },
	{ name: 'server', icon: IconServer },
	{ name: 'package', icon: IconPackage },
	{ name: 'box', icon: IconBox },
	{ name: 'stack-2', icon: IconStack2 },
	{ name: 'news', icon: IconNews },
	{ name: 'chair-director', icon: IconChairDirector },
	{ name: 'vector-bezier', icon: IconVectorBezier },
	{ name: 'brush', icon: IconBrush },
	{ name: 'flask', icon: IconFlask },
	{ name: 'atom', icon: IconAtom },
	{ name: 'telescope', icon: IconTelescope }
];

const iconByName = new Map(curatedIcons.map((entry) => [entry.name, entry.icon]));

export function getCuratedIcon(name: string): Icon | undefined {
	return iconByName.get(name);
}
