import {
	Gamepad2,
	Music,
	Video,
	Camera,
	Palette,
	Code2,
	Terminal,
	Wrench,
	BookOpen,
	GraduationCap,
	Briefcase,
	Calculator,
	Calendar,
	Mail,
	MessageCircle,
	Users,
	Heart,
	Star,
	Bookmark,
	Folder,
	FileText,
	Image,
	Film,
	Headphones,
	Mic,
	Radio,
	Tv,
	Monitor,
	Smartphone,
	Globe,
	Map as MapIcon,
	Compass,
	Rocket,
	Plane,
	Car,
	Bike,
	Coffee,
	ShoppingCart,
	Wallet,
	Shield,
	Lock,
	Key,
	Cloud,
	Sun,
	Moon,
	Zap,
	Flame,
	Leaf,
	Trees,
	Mountain,
	Home,
	Wifi,
	Puzzle,
	Dices,
	Trophy,
	Target,
	Swords,
	Ghost,
	PawPrint,
	Bug,
	Bot,
	Cpu,
	Database,
	Server,
	Package,
	Box,
	Layers,
	Newspaper,
	Clapperboard,
	PenTool,
	Brush,
	FlaskConical,
	Atom,
	Telescope,
	type LucideProps
} from '@lucide/svelte';
import type { Component } from 'svelte';

export const curatedIcons: { name: string; icon: Component<LucideProps> }[] = [
	{ name: 'Gamepad2', icon: Gamepad2 },
	{ name: 'Music', icon: Music },
	{ name: 'Video', icon: Video },
	{ name: 'Camera', icon: Camera },
	{ name: 'Palette', icon: Palette },
	{ name: 'Code2', icon: Code2 },
	{ name: 'Terminal', icon: Terminal },
	{ name: 'Wrench', icon: Wrench },
	{ name: 'BookOpen', icon: BookOpen },
	{ name: 'GraduationCap', icon: GraduationCap },
	{ name: 'Briefcase', icon: Briefcase },
	{ name: 'Calculator', icon: Calculator },
	{ name: 'Calendar', icon: Calendar },
	{ name: 'Mail', icon: Mail },
	{ name: 'MessageCircle', icon: MessageCircle },
	{ name: 'Users', icon: Users },
	{ name: 'Heart', icon: Heart },
	{ name: 'Star', icon: Star },
	{ name: 'Bookmark', icon: Bookmark },
	{ name: 'Folder', icon: Folder },
	{ name: 'FileText', icon: FileText },
	{ name: 'Image', icon: Image },
	{ name: 'Film', icon: Film },
	{ name: 'Headphones', icon: Headphones },
	{ name: 'Mic', icon: Mic },
	{ name: 'Radio', icon: Radio },
	{ name: 'Tv', icon: Tv },
	{ name: 'Monitor', icon: Monitor },
	{ name: 'Smartphone', icon: Smartphone },
	{ name: 'Globe', icon: Globe },
	{ name: 'Map', icon: MapIcon },
	{ name: 'Compass', icon: Compass },
	{ name: 'Rocket', icon: Rocket },
	{ name: 'Plane', icon: Plane },
	{ name: 'Car', icon: Car },
	{ name: 'Bike', icon: Bike },
	{ name: 'Coffee', icon: Coffee },
	{ name: 'ShoppingCart', icon: ShoppingCart },
	{ name: 'Wallet', icon: Wallet },
	{ name: 'Shield', icon: Shield },
	{ name: 'Lock', icon: Lock },
	{ name: 'Key', icon: Key },
	{ name: 'Cloud', icon: Cloud },
	{ name: 'Sun', icon: Sun },
	{ name: 'Moon', icon: Moon },
	{ name: 'Zap', icon: Zap },
	{ name: 'Flame', icon: Flame },
	{ name: 'Leaf', icon: Leaf },
	{ name: 'Trees', icon: Trees },
	{ name: 'Mountain', icon: Mountain },
	{ name: 'Home', icon: Home },
	{ name: 'Wifi', icon: Wifi },
	{ name: 'Puzzle', icon: Puzzle },
	{ name: 'Dices', icon: Dices },
	{ name: 'Trophy', icon: Trophy },
	{ name: 'Target', icon: Target },
	{ name: 'Swords', icon: Swords },
	{ name: 'Ghost', icon: Ghost },
	{ name: 'PawPrint', icon: PawPrint },
	{ name: 'Bug', icon: Bug },
	{ name: 'Bot', icon: Bot },
	{ name: 'Cpu', icon: Cpu },
	{ name: 'Database', icon: Database },
	{ name: 'Server', icon: Server },
	{ name: 'Package', icon: Package },
	{ name: 'Box', icon: Box },
	{ name: 'Layers', icon: Layers },
	{ name: 'Newspaper', icon: Newspaper },
	{ name: 'Clapperboard', icon: Clapperboard },
	{ name: 'PenTool', icon: PenTool },
	{ name: 'Brush', icon: Brush },
	{ name: 'FlaskConical', icon: FlaskConical },
	{ name: 'Atom', icon: Atom },
	{ name: 'Telescope', icon: Telescope }
];

const iconByName = new Map(curatedIcons.map((entry) => [entry.name, entry.icon]));

export function getCuratedIcon(name: string): Component<LucideProps> | undefined {
	return iconByName.get(name);
}
