import { Client } from 'ssh2';
import sshpk from 'sshpk';
import { XMLParser } from 'fast-xml-parser';
import { db } from './db';
import { decryptSecret } from './secrets';
import { notifyUser } from './notifications';
import { uploadFile } from './bunny';
import type { FlatpakApp, InfraSettings } from '$lib/generated/prisma/client';

export function generateSshKeypair(): { publicKey: string; privateKeyOpenSsh: string } {
	const key = sshpk.generatePrivateKey('ed25519');
	key.comment = 'forge@blossomos';
	return {
		publicKey: key.toPublic().toString('ssh'),
		privateKeyOpenSsh: key.toString('openssh')
	};
}

// Builds the full remote pipeline as a single self-deleting script. The GPG key ID is
// derived dynamically on the remote host (matching the user's existing tooling) rather
// than stored anywhere. Deliberately does NOT force-delete the appstream2/x86_64 ref
// before regenerating: that's a manual repair step for when the branch is already
// broken, not something to run on every routine publish, doing it unconditionally
// disconnects the ref's history from what existing clients have cached, which can
// surface as a static-delta checksum mismatch on their next pull.
//
// Deliberately does NOT check out the tree and inject/overwrite any metainfo.xml or
// app-info/xmls fragment of its own anymore. That used to be necessary because Forge's
// web form collected name/summary/icon/etc as free text with no relation to what was
// actually inside the bundle, so something had to write real AppStream data into the
// tree. Now that submission (see extractAppstreamMetadata below) reads the bundle's
// OWN real AppStream data instead of asking the developer to retype it, that data is
// already correct and already in the tree from build-import-bundle, overwriting it
// only risked leaving stale, inconsistent leftovers (e.g. a real bundle's own
// `files/share/app-info/icons/flatpak/*` icon cache, generated by the developer's own
// `appstreamcli compose` step, sitting orphaned next to a hand-written xml.gz that no
// longer referenced it) without actually fixing anything. Publishing is now just:
// validate in staging, copy the untouched commit into the shared repo, and let
// build-update-repo compose the aggregate catalog from what's really there.
const GIT_COMMIT_MARKER = 'FORGE_GIT_COMMIT=';

// Shared by every remote script that needs build scratch space (buildRemoteScript,
// buildExtractScript). Defaults to mktemp's own default TMPDIR, which on some hosts
// sits on a partition too small for a flatpak-builder build or a multi-GB bundle
// download. settings.buildWorkDir lets an admin point that scratch space at a
// larger disk instead. mkdir -p plus set -e means a misconfigured/unwritable path
// fails the script immediately with mkdir's own error, rather than surfacing later
// as an opaque "No space left on device" mid-build.
function buildWorkdirSetup(settings: InfraSettings): string {
	if (!settings.buildWorkDir) return 'WORKDIR=$(mktemp -d)';
	return `mkdir -p "${settings.buildWorkDir}"
WORKDIR=$(mktemp -d -p "${settings.buildWorkDir}")`;
}

// Bundles are self-describing: build-import-bundle always imports under the
// bundle's OWN embedded appid/branch, regardless of what this submission
// declared. Git manifests declare their own app-id the same way. Importing
// straight into $REPO_PATH and only checking the ref afterward would leave a
// real, signed commit sitting in the shared repo on a mismatch, nothing ever
// cleans that up, and every later aggregate appstream2 rebuild sweeps it back
// in. Staging first (both source types build into $STAGING_REPO) means a
// mismatch never touches the shared repo at all.
function buildSourceSection(app: FlatpakApp): string {
	if (app.sourceType === 'GIT') {
		return `
GIT_URL="${app.gitUrl}"
GIT_BRANCH="${app.gitBranch}"
MANIFEST_PATH="${app.gitManifestPath}"

git clone --branch "$GIT_BRANCH" --depth 1 "$GIT_URL" src
echo "${GIT_COMMIT_MARKER}$(git -C src rev-parse HEAD)"

# --disable-rofiles-fuse: FUSE may not be available/permitted on the remote
# host, matching the same "don't assume privileged capabilities" lesson as
# ostree checkout's -U flag elsewhere in this file. --state-dir explicitly
# inside $WORKDIR avoids flatpak-builder's cache dir landing on a different
# filesystem than the build/target dirs, which it refuses to do.
flatpak-builder --gpg-sign="$GPG_ID" --repo="$STAGING_REPO" \\
  --state-dir="$WORKDIR/.flatpak-builder" --force-clean --disable-rofiles-fuse \\
  "$WORKDIR/build-dir" "src/$MANIFEST_PATH"

# Unlike a bundle submission (extracted once at upload time, see
# extractAppstreamMetadata), a git submission has no AppStream data to show in
# Forge's own UI until a build actually produces it. Read it back out of what
# was just built, same marker technique as buildExtractScript, so runPublish
# can update the app's display fields after every successful (re)build.
GIT_BUILT_REF=$(ostree refs --repo="$STAGING_REPO" | grep "^app/$APPID/" | head -n1)
if [ -n "$GIT_BUILT_REF" ]; then
  ostree checkout -U --repo="$STAGING_REPO" "$GIT_BUILT_REF" post-build-checkout
  # Named exactly $APPID, never a bare '*.xml'/'*.png' glob: a git build's tree
  # isn't just the submitted app, it's also whatever base app/SDK
  # extension/module the manifest pulled in (e.g. org.winehq.Wine as a base,
  # or a bundled qemu module), and those ship their own metainfo/icon files
  # in the exact same directories. An unscoped glob has no guarantee of
  # landing on the submitted app's own file over one of those.
  GIT_METAINFO_PATH=$(find post-build-checkout/files/share/metainfo post-build-checkout/export/share/metainfo -maxdepth 1 \\( -name "$APPID.metainfo.xml" -o -name "$APPID.appdata.xml" \\) 2>/dev/null | head -n1 || true)
  if [ -n "$GIT_METAINFO_PATH" ]; then
    echo "${EXTRACT_METAINFO_START}"
    base64 -w0 "$GIT_METAINFO_PATH"
    echo ""
    echo "${EXTRACT_METAINFO_END}"
  fi
  # Sized PNGs first, then scalable/apps as a fallback: some manifests only
  # ship an svg there (no raster icon at all), and some mistakenly install a
  # raster png into scalable/apps instead of a proper sized directory.
  GIT_ICON_PATH=$(ls post-build-checkout/files/share/icons/hicolor/256x256/apps/"$APPID".png \\
    post-build-checkout/files/share/icons/hicolor/128x128/apps/"$APPID".png \\
    post-build-checkout/files/share/icons/hicolor/64x64/apps/"$APPID".png \\
    post-build-checkout/files/share/icons/hicolor/48x48/apps/"$APPID".png \\
    post-build-checkout/files/share/icons/hicolor/scalable/apps/"$APPID".svg \\
    post-build-checkout/files/share/icons/hicolor/scalable/apps/"$APPID".png 2>/dev/null | head -n1 || true)
  if [ -n "$GIT_ICON_PATH" ]; then
    echo "${EXTRACT_ICON_START}"
    base64 -w0 "$GIT_ICON_PATH"
    echo ""
    echo "${EXTRACT_ICON_END}"
  fi
fi
`;
	}

	return `
BUNDLE_URL="${app.bundleUrl}"

curl -fsSL "$BUNDLE_URL" -o bundle.flatpak

flatpak build-import-bundle --gpg-sign="$GPG_ID" "$STAGING_REPO" bundle.flatpak
`;
}

// passphraseFilePath: unlike buildRepairScript/buildUnpublishScript (still piped
// over exec's stdin, see execScript), this script runs detached inside a `screen`
// session with no interactive stdin to receive anything - the passphrase has to
// arrive as a file instead. Deleted via the trap the moment it's read, same
// self-deleting treatment the script already gives itself.
function buildRemoteScript(
	app: FlatpakApp,
	settings: InfraSettings,
	passphraseFilePath: string
): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0" "${passphraseFilePath}"; [ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

GPG_PASSPHRASE=$(cat "${passphraseFilePath}")

REPO_PATH="${settings.remoteRepoPath}"
APPID="${app.appid}"

GPG_ID=$(gpg --list-secret-keys --keyid-format LONG | awk '/sec/ {print $2}' | cut -d/ -f2)
KEYGRIP=$(gpg --with-keygrip -K "$GPG_ID" | awk '/Keygrip/ {print $3; exit}')
/usr/libexec/gpg-preset-passphrase --preset "$KEYGRIP" <<< "$GPG_PASSPHRASE"

${buildWorkdirSetup(settings)}
cd "$WORKDIR"

STAGING_REPO="$WORKDIR/staging-repo"
ostree init --repo="$STAGING_REPO" --mode=archive-z2

${buildSourceSection(app)}

REF=$(ostree refs --repo="$STAGING_REPO" | grep "^app/$APPID/" | head -n1)
if [ -z "$REF" ]; then
  # Themes/extensions publish as a runtime rather than an app, see extractAppstreamMetadata.
  REF=$(ostree refs --repo="$STAGING_REPO" | grep "^runtime/$APPID/" | head -n1)
fi
if [ -z "$REF" ]; then
  echo "Could not find a matching app or runtime ref for $APPID after building (appid/branch mismatch, or the build didn't produce a ref) - refusing to publish to the shared repo" >&2
  exit 1
fi

ostree pull-local --repo="$REPO_PATH" "$STAGING_REPO" "$REF"

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"

echo "FORGE_PUBLISH_OK"
`;
}

function sftpWriteFile(
	conn: Client,
	remotePath: string,
	contents: string,
	mode = 0o700
): Promise<void> {
	return new Promise((resolve, reject) => {
		conn.sftp((err, sftp) => {
			if (err) return reject(err);
			sftp.writeFile(remotePath, contents, { mode }, (writeErr) => {
				if (writeErr) return reject(writeErr);
				resolve();
			});
		});
	});
}

// Like execScript, but for commands that don't need a piped stdin (the launch and
// poll steps of the detached-build flow below never pipe the GPG passphrase over
// exec - see buildRemoteScript's passphraseFilePath for why).
function execCommand(conn: Client, command: string): Promise<{ exitCode: number; output: string }> {
	return new Promise((resolve, reject) => {
		conn.exec(command, (err, stream) => {
			if (err) return reject(err);
			let output = '';
			stream.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8');
			});
			stream.stderr.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8');
			});
			stream.on('close', (exitCode: number) => {
				resolve({ exitCode: exitCode ?? 1, output });
			});
			stream.on('error', reject);
		});
	});
}

function execScript(
	conn: Client,
	remotePath: string,
	gpgPassphrase: string
): Promise<{ exitCode: number; log: string }> {
	return new Promise((resolve, reject) => {
		conn.exec(`bash ${remotePath}`, (err, stream) => {
			if (err) return reject(err);
			let log = '';
			stream.on('data', (chunk: Buffer) => {
				log += chunk.toString('utf8');
			});
			stream.stderr.on('data', (chunk: Buffer) => {
				log += chunk.toString('utf8');
			});
			stream.on('close', (exitCode: number) => {
				resolve({ exitCode: exitCode ?? 1, log });
			});
			stream.on('error', reject);
			stream.end(`${gpgPassphrase}\n`);
		});
	});
}

function connect(settings: InfraSettings, privateKey: string): Promise<Client> {
	return new Promise((resolve, reject) => {
		const conn = new Client();
		conn.on('ready', () => resolve(conn));
		conn.on('error', reject);
		conn.connect({
			host: settings.remoteHost,
			username: settings.remoteUser,
			privateKey
		});
	});
}

// Manual, explicitly-triggered repair for when the appstream2/x86_64 branch is
// already broken/stale, not run automatically as part of routine publishing
// (see buildRemoteScript's comment for why that caused real corruption once).
function buildRepairScript(settings: InfraSettings): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0"' EXIT

IFS= read -r GPG_PASSPHRASE

REPO_PATH="${settings.remoteRepoPath}"

GPG_ID=$(gpg --list-secret-keys --keyid-format LONG | awk '/sec/ {print $2}' | cut -d/ -f2)
KEYGRIP=$(gpg --with-keygrip -K "$GPG_ID" | awk '/Keygrip/ {print $3; exit}')
/usr/libexec/gpg-preset-passphrase --preset "$KEYGRIP" <<< "$GPG_PASSPHRASE"

ostree refs --repo="$REPO_PATH" appstream2/x86_64 --delete || true

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"

echo "FORGE_REPAIR_OK"
`;
}

// Shared by repairAppstream/unpublishFlatpak/runPublish: loads infra settings, connects,
// writes the given script over SFTP, runs it with the passphrase piped over stdin, and
// always tears the connection down. Never throws, callers get {ok, log} either way.
async function runOnRemote(
	scriptBuilder: (settings: InfraSettings) => string,
	remotePathPrefix: string
): Promise<{ ok: boolean; exitCode: number | null; log: string }> {
	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (!settings?.sshPrivateKeyEncrypted || !settings.gpgPassphraseEncrypted) {
		return {
			ok: false,
			exitCode: null,
			log: 'Infra settings are not fully configured (missing SSH key or GPG passphrase).'
		};
	}

	let conn: Client | undefined;
	try {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		const gpgPassphrase = decryptSecret(settings.gpgPassphraseEncrypted);
		const script = scriptBuilder(settings);
		const remotePath = `${remotePathPrefix}-${Date.now()}.sh`;

		conn = await connect(settings, privateKey);
		await sftpWriteFile(conn, remotePath, script);
		const { exitCode, log } = await execScript(conn, remotePath, gpgPassphrase);
		return { ok: exitCode === 0, exitCode, log };
	} catch (e) {
		return { ok: false, exitCode: null, log: e instanceof Error ? e.message : String(e) };
	} finally {
		conn?.end();
	}
}

export async function repairAppstream(): Promise<{ ok: boolean; log: string }> {
	return runOnRemote(buildRepairScript, '/tmp/forge-repair');
}

const EXTRACT_METAINFO_START = 'FORGE_METAINFO_B64_START';
const EXTRACT_METAINFO_END = 'FORGE_METAINFO_B64_END';
const EXTRACT_ICON_START = 'FORGE_ICON_B64_START';
const EXTRACT_ICON_END = 'FORGE_ICON_B64_END';

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

// The extraction scripts now fall back to hicolor/scalable/apps/$APPID.svg
// when no sized raster icon exists, so an extracted icon is no longer
// guaranteed to be a PNG, callers must not assume the extension/mime type.
export function iconFileExtension(buffer: Buffer): 'png' | 'svg' {
	return buffer.subarray(0, 4).equals(PNG_MAGIC) ? 'png' : 'svg';
}

// Read-only: imports the bundle into a throwaway staging repo (never touches the
// shared repo) purely to read back its own, real AppStream metainfo.xml and icon, so
// Forge's web UI can be populated from what's actually inside the bundle instead of
// free-text form fields a developer could type anything into.
function buildExtractScript(bundleUrl: string, settings: InfraSettings): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap '[ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

BUNDLE_URL="${bundleUrl}"

${buildWorkdirSetup(settings)}
cd "$WORKDIR"

echo "FORGE_STEP: downloading bundle"
curl -fsSL "$BUNDLE_URL" -o bundle.flatpak

STAGING_REPO="$WORKDIR/staging-repo"
echo "FORGE_STEP: initializing staging repo"
ostree init --repo="$STAGING_REPO" --mode=archive-z2
echo "FORGE_STEP: importing bundle"
flatpak build-import-bundle "$STAGING_REPO" bundle.flatpak

echo "FORGE_STEP: resolving ref"
# grep exits non-zero when a bundle has no app/ ref at all (e.g. a runtime-only
# bundle, see below), which under set -e -o pipefail would otherwise kill the
# whole script right here before the runtime fallback ever runs.
REF=$(ostree refs --repo="$STAGING_REPO" | grep "^app/" | head -n1 || true)
if [ -z "$REF" ]; then
  # Not every submission is a user-facing app, GTK/Qt themes and other extensions
  # ship as a runtime instead, those have no .desktop file or per-app metainfo.xml,
  # but are still a legitimate thing to host, so accept them too.
  REF=$(ostree refs --repo="$STAGING_REPO" | grep "^runtime/" | head -n1 || true)
fi
if [ -z "$REF" ]; then
  echo "Uploaded file has no importable Flatpak app or runtime ref" >&2
  exit 1
fi
APPID=$(echo "$REF" | cut -d/ -f2)
echo "FORGE_APPID=$APPID"
echo "FORGE_REF=$REF"

echo "FORGE_STEP: checking out ref"
ostree checkout -U --repo="$STAGING_REPO" "$REF" checkout

# metainfo.xml is optional, a runtime typically doesn't ship one, missing metainfo
# just means the name/summary/description/icon fall back to placeholders below
# rather than blocking the submission entirely.
echo "FORGE_STEP: looking for metainfo.xml"
# Named exactly $APPID, not a bare '*.xml' glob, same reasoning as the git
# build path below: a base app/SDK extension baked into the bundle can ship
# its own metainfo/icon in the same directories as the submitted app's own.
METAINFO_PATH=$(find checkout/files/share/metainfo checkout/export/share/metainfo -maxdepth 1 \\( -name "$APPID.metainfo.xml" -o -name "$APPID.appdata.xml" \\) 2>/dev/null | head -n1 || true)
if [ -n "$METAINFO_PATH" ]; then
  echo "${EXTRACT_METAINFO_START}"
  base64 -w0 "$METAINFO_PATH"
  echo ""
  echo "${EXTRACT_METAINFO_END}"
fi

echo "FORGE_STEP: looking for an icon"
# Sized PNGs first, then scalable/apps as a fallback (svg-only icon, or a
# raster png mistakenly installed into scalable/apps instead of a sized dir).
ICON_PATH=$(ls checkout/files/share/icons/hicolor/256x256/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/128x128/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/64x64/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/48x48/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/scalable/apps/"$APPID".svg \\
  checkout/files/share/icons/hicolor/scalable/apps/"$APPID".png 2>/dev/null | head -n1 || true)
if [ -n "$ICON_PATH" ]; then
  echo "${EXTRACT_ICON_START}"
  base64 -w0 "$ICON_PATH"
  echo ""
  echo "${EXTRACT_ICON_END}"
fi

echo "FORGE_EXTRACT_OK"
`;
}

function extractBetweenMarkers(
	log: string,
	startMarker: string,
	endMarker: string
): string | undefined {
	const start = log.indexOf(startMarker);
	if (start === -1) return undefined;
	const contentStart = start + startMarker.length;
	const end = log.indexOf(endMarker, contentStart);
	if (end === -1) return undefined;
	return log.slice(contentStart, end).trim();
}

// AppStream allows both the older <developer_name> and the newer <developer><name>
// form, and either can appear as a plain string or as an object with a #text node
// depending on whether the parser sees attributes alongside it. A translated
// component (multiple <name>/<summary> elements with different xml:lang) parses
// to an ARRAY of those, which is also `typeof === 'object'` but has no '#text' of
// its own - without this branch every one of these fields silently came back
// empty for any bundle with translated AppStream metadata.
function textOf(value: unknown): string {
	if (typeof value === 'string') return value;
	if (Array.isArray(value)) {
		// Prefer the untranslated/default entry (no xml:lang) for single-value
		// fields, these aren't meant to be localized themselves.
		const untranslated = value.find(
			(v) => typeof v === 'string' || !('@_xml:lang' in (v as Record<string, unknown>))
		);
		return textOf(untranslated ?? value[0]);
	}
	if (value && typeof value === 'object' && '#text' in (value as Record<string, unknown>)) {
		return String((value as Record<string, unknown>)['#text'] ?? '');
	}
	return '';
}

export type LocalizedMetadata = { name: string; summary: string; description: string };

function collectLangVariants(value: unknown): Record<string, string> {
	const items = Array.isArray(value) ? value : value !== undefined && value !== null ? [value] : [];
	const result: Record<string, string> = {};
	for (const item of items) {
		if (typeof item === 'string') {
			if (item.trim()) result.en = item.trim();
			continue;
		}
		if (item && typeof item === 'object') {
			const obj = item as Record<string, unknown>;
			const lang = typeof obj['@_xml:lang'] === 'string' ? (obj['@_xml:lang'] as string) : 'en';
			const text = textOf(obj).trim();
			if (text) result[lang] = text;
		}
	}
	return result;
}

// <description> blocks carry their own inner markup verbatim (see the comment
// on the single-value extraction below), so translated variants are pulled the
// same way, by matching each <description>/<description xml:lang="..."> block
// directly out of the source XML rather than the parsed object tree.
function collectDescriptionVariants(xml: string): Record<string, string> {
	const result: Record<string, string> = {};
	const regex = /<description(?:\s+xml:lang="([^"]+)")?\s*>([\s\S]*?)<\/description>/g;
	let match: RegExpExecArray | null;
	while ((match = regex.exec(xml))) {
		const lang = match[1] || 'en';
		const text = match[2].trim();
		if (text) result[lang] = text;
	}
	return result;
}

// Preview-only: the real submission fields (parseAppstreamComponent, used for
// what's actually saved) are intentionally single-language, Flatpak has no
// translation model the way PwaTranslation exists for PWAs. This just surfaces
// every language actually present in the bundle's own metainfo.xml so a
// submitter can double check translated listings before submitting.
export function parseAppstreamTranslations(xml: string): Record<string, LocalizedMetadata> {
	const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });
	const doc = parser.parse(xml) as Record<string, unknown>;
	const component = (doc.component ?? {}) as Record<string, unknown>;

	const names = collectLangVariants(component.name);
	const summaries = collectLangVariants(component.summary);
	const descriptions = collectDescriptionVariants(xml);

	const langs = new Set([
		...Object.keys(names),
		...Object.keys(summaries),
		...Object.keys(descriptions)
	]);
	if (langs.size === 0) langs.add('en');

	const result: Record<string, LocalizedMetadata> = {};
	for (const lang of langs) {
		result[lang] = {
			name: names[lang] ?? names.en ?? '',
			summary: summaries[lang] ?? summaries.en ?? '',
			description: descriptions[lang] ?? descriptions.en ?? ''
		};
	}
	return result;
}

function parseAppstreamComponent(xml: string): {
	name: string;
	summary: string;
	description: string;
	developerName: string;
	homepageUrl: string;
	screenshots: string[];
} {
	const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });
	const doc = parser.parse(xml) as Record<string, unknown>;
	const component = (doc.component ?? {}) as Record<string, unknown>;

	const name = textOf(component.name).trim();
	const summary = textOf(component.summary).trim();

	// Description is a mix of <p>/<ul>/<ol>/<li> elements meant to be shown as HTML
	// (matches Forge's existing "Description (HTML)" field), pulling the raw inner
	// XML straight out of the source string preserves that markup exactly, rather
	// than trying to reconstruct it from the parsed object tree.
	const descMatch = xml.match(/<description>([\s\S]*?)<\/description>/);
	const description = descMatch ? descMatch[1].trim() : '';

	let developerName = textOf(component.developer_name).trim();
	if (!developerName && component.developer && typeof component.developer === 'object') {
		developerName = textOf((component.developer as Record<string, unknown>).name).trim();
	}

	let homepageUrl = '';
	const urlsRaw = component.url;
	const urls = Array.isArray(urlsRaw) ? urlsRaw : urlsRaw ? [urlsRaw] : [];
	for (const u of urls as Record<string, unknown>[]) {
		if (u?.['@_type'] === 'homepage') homepageUrl = textOf(u).trim();
	}

	const screenshots: string[] = [];
	const shotsRaw = (component.screenshots as Record<string, unknown> | undefined)?.screenshot;
	const shots = Array.isArray(shotsRaw) ? shotsRaw : shotsRaw ? [shotsRaw] : [];
	for (const s of shots as Record<string, unknown>[]) {
		const url = textOf(s?.image).trim();
		if (url) screenshots.push(url);
	}

	return { name, summary, description, developerName, homepageUrl, screenshots };
}

export type ExtractedAppstream = {
	ok: boolean;
	appid?: string;
	branch?: string;
	name?: string;
	summary?: string;
	description?: string;
	developerName?: string;
	homepageUrl?: string;
	screenshots?: string[];
	iconBuffer?: Buffer;
	translations?: Record<string, LocalizedMetadata>;
	error?: string;
	log?: string;
};

export async function extractAppstreamMetadata(bundleUrl: string): Promise<ExtractedAppstream> {
	const { ok, exitCode, log } = await runOnRemote(
		(settings) => buildExtractScript(bundleUrl, settings),
		'/tmp/forge-extract'
	);
	if (!ok || !log.includes('FORGE_EXTRACT_OK')) {
		// The last line isn't necessarily the actual failure, a step can print a
		// perfectly normal progress message and then die with no further output at
		// all (connection drop, remote process killed, out of disk, etc.), so the
		// headline names the last step reached instead of guessing at an error
		// line, the full log (always returned below) has the real detail.
		const lastStepMatch = [...log.matchAll(/^FORGE_STEP: (.+)$/gm)].pop();
		const lastStep = lastStepMatch?.[1];
		const codeDesc =
			exitCode === null ? 'the connection to the signing host failed' : `exit code ${exitCode}`;
		return {
			ok: false,
			error: lastStep
				? `Extraction failed after "${lastStep}" (${codeDesc}) - see log below`
				: `Extraction failed (${codeDesc}) - see log below`,
			log
		};
	}

	const appidMatch = log.match(/^FORGE_APPID=(.+)$/m);
	const refMatch = log.match(/^FORGE_REF=(.+)$/m);
	const metainfoB64 = extractBetweenMarkers(
		log,
		EXTRACT_METAINFO_START,
		EXTRACT_METAINFO_END
	)?.replace(/\s+/g, '');
	const iconB64 = extractBetweenMarkers(log, EXTRACT_ICON_START, EXTRACT_ICON_END)?.replace(
		/\s+/g,
		''
	);

	if (!appidMatch) {
		return { ok: false, error: 'Could not determine an app id for the uploaded bundle', log };
	}

	const appid = appidMatch[1].trim();
	const branch = refMatch ? refMatch[1].trim().split('/').pop() : 'stable';
	const iconBuffer = iconB64 ? Buffer.from(iconB64, 'base64') : undefined;
	const metainfoXml = metainfoB64 ? Buffer.from(metainfoB64, 'base64').toString('utf8') : undefined;
	const parsed = metainfoXml
		? parseAppstreamComponent(metainfoXml)
		: {
				name: '',
				summary: '',
				description: '',
				developerName: '',
				homepageUrl: '',
				screenshots: []
			};
	const translations = metainfoXml ? parseAppstreamTranslations(metainfoXml) : undefined;

	return { ok: true, appid, branch, iconBuffer, translations, log, ...parsed };
}

// Removes a specific app's ref from the repo (if present) and republishes, so the
// repo's summary/deltas/appstream catalog no longer advertise it. Used both by a
// reviewer's explicit "pull" and by deleting a Flatpak that's currently live.
function buildUnpublishScript(app: FlatpakApp, settings: InfraSettings): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0"' EXIT

IFS= read -r GPG_PASSPHRASE

REPO_PATH="${settings.remoteRepoPath}"
APPID="${app.appid}"

GPG_ID=$(gpg --list-secret-keys --keyid-format LONG | awk '/sec/ {print $2}' | cut -d/ -f2)
KEYGRIP=$(gpg --with-keygrip -K "$GPG_ID" | awk '/Keygrip/ {print $3; exit}')
/usr/libexec/gpg-preset-passphrase --preset "$KEYGRIP" <<< "$GPG_PASSPHRASE"

REF=$(ostree refs --repo="$REPO_PATH" | grep "^app/$APPID/" | head -n1)
if [ -n "$REF" ]; then
  ostree refs --repo="$REPO_PATH" "$REF" --delete
fi

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"

echo "FORGE_UNPUBLISH_OK"
`;
}

export async function unpublishFlatpak(app: FlatpakApp): Promise<{ ok: boolean; log: string }> {
	return runOnRemote(
		(settings) => buildUnpublishScript(app, settings),
		`/tmp/forge-unpublish-${app.id}`
	);
}

// Only relevant for GIT-sourced apps: a bundle submission already extracted its
// display data once at upload time (see extractAppstreamMetadata), but a git
// submission has nothing to show until a build actually produces AppStream data,
// so it's re-read from the build log (see buildSourceSection's GIT branch) after
// every successful (re)build instead.
async function updateDisplayDataFromBuildLog(
	appId: string,
	log: string
): Promise<Record<string, unknown>> {
	const metainfoB64 = extractBetweenMarkers(
		log,
		EXTRACT_METAINFO_START,
		EXTRACT_METAINFO_END
	)?.replace(/\s+/g, '');
	if (!metainfoB64) return {};

	const metainfoXml = Buffer.from(metainfoB64, 'base64').toString('utf8');
	const parsed = parseAppstreamComponent(metainfoXml);

	const data: Record<string, unknown> = {
		name: parsed.name || undefined,
		summary: parsed.summary || undefined,
		description: parsed.description || undefined,
		homepageUrl: parsed.homepageUrl || undefined,
		screenshots: parsed.screenshots.length ? parsed.screenshots : undefined
	};

	const iconB64 = extractBetweenMarkers(log, EXTRACT_ICON_START, EXTRACT_ICON_END)?.replace(
		/\s+/g,
		''
	);
	if (iconB64) {
		const iconBuffer = Buffer.from(iconB64, 'base64');
		const iconArrayBuffer = iconBuffer.buffer.slice(
			iconBuffer.byteOffset,
			iconBuffer.byteOffset + iconBuffer.byteLength
		) as ArrayBuffer;
		data.iconUrl = await uploadFile(
			iconArrayBuffer,
			`${appId}-icon.${iconFileExtension(iconBuffer)}`
		);
	}

	return Object.fromEntries(Object.entries(data).filter(([, v]) => v !== undefined));
}

// Bounded tail read for both the live-view refresh and the final stored log -
// generous enough for any real build, matches the "read a bounded amount"
// posture already used elsewhere in this file (e.g. notification bodies).
const LOG_READ_BYTES = 5_000_000;
const POLL_SPLIT_MARKER = '__FORGE_POLL_SPLIT__';
const POLL_INTERVAL_MS = 7_000;

interface RemoteBuildPaths {
	scriptPath: string;
	logPath: string;
	exitPath: string;
	passphrasePath: string;
	sessionName: string;
}

function remoteBuildPaths(appId: string): RemoteBuildPaths {
	const base = `/tmp/forge-publish-${appId}-${Date.now()}`;
	return {
		scriptPath: `${base}.sh`,
		logPath: `${base}.log`,
		exitPath: `${base}.exit`,
		passphrasePath: `${base}.pass`,
		sessionName: `forge-build-${appId}-${Date.now()}`
	};
}

// Writes the build script + a short-lived passphrase file, then launches the
// script detached inside a `screen` session and returns as soon as that launch
// itself completes (near-instant, `-dm` never attaches). The build keeps
// running on the remote host independent of this SSH connection, this Node
// process, or Forge restarting - see pollBuildOnce for how its outcome is
// picked back up. Requires `screen` on the remote host (same "assume it's
// already there" posture as flatpak-builder/gpg/git elsewhere in this file).
// Note: a remote host with systemd-logind's KillUserProcesses=yes will kill a
// detached screen session on SSH logout same as any other process - if builds
// still die on disconnect, `loginctl enable-linger <remoteUser>` is the fix.
async function launchRemoteBuild(
	app: FlatpakApp,
	settings: InfraSettings,
	paths: RemoteBuildPaths
): Promise<{ ok: boolean; log: string }> {
	if (!settings.sshPrivateKeyEncrypted || !settings.gpgPassphraseEncrypted) {
		return {
			ok: false,
			log: 'Infra settings are not fully configured (missing SSH key or GPG passphrase).'
		};
	}

	let conn: Client | undefined;
	try {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		const gpgPassphrase = decryptSecret(settings.gpgPassphraseEncrypted);
		const script = buildRemoteScript(app, settings, paths.passphrasePath);

		conn = await connect(settings, privateKey);
		await sftpWriteFile(conn, paths.scriptPath, script);
		await sftpWriteFile(conn, paths.passphrasePath, gpgPassphrase, 0o600);

		const launchCommand = `screen -dmS "${paths.sessionName}" bash -c 'bash "${paths.scriptPath}" > "${paths.logPath}" 2>&1; echo $? > "${paths.exitPath}"'`;
		const { exitCode, output } = await execCommand(conn, launchCommand);
		if (exitCode !== 0) {
			return {
				ok: false,
				log: `Failed to launch detached build (screen exited ${exitCode}): ${output}`
			};
		}
		return { ok: true, log: '' };
	} catch (e) {
		return { ok: false, log: e instanceof Error ? e.message : String(e) };
	} finally {
		conn?.end();
	}
}

// Builds currently being tracked by the poller below - populated by triggerPublish
// right after a successful launch, and by reconcileStuckBuilds on server startup.
const activeBuildIds = new Set<string>();

// One poll tick for one build: opens a fresh short-lived SSH connection (never
// the one that launched it), checks whether the exit-marker file exists yet,
// and either refreshes the live log (still running) or finalizes (done).
//
// Finalizing is deliberately idempotent and safe to retry: the tracked build id
// is only removed from activeBuildIds, and the remote log/exit files are only
// deleted, *after* the DB writes below actually succeed. If they throw (e.g.
// the exact transient Postgres error that originally left a row stuck on
// PROCESSING forever), this function just logs it and returns - the exit file
// is still sitting there, so the very next tick (~POLL_INTERVAL_MS later)
// re-reads it and retries the same finalize from scratch. No bespoke
// backoff/retry helper needed: a blip under one interval self-heals silently,
// a longer outage self-heals whenever Postgres comes back, and a Forge restart
// mid-outage is covered by reconcileStuckBuilds re-discovering the same build.
async function pollBuildOnce(buildId: string): Promise<void> {
	const build = await db.flatpakBuild.findUnique({
		where: { id: buildId },
		include: { flatpakApp: true }
	});
	if (!build || build.finishedAt) {
		activeBuildIds.delete(buildId);
		return;
	}

	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (!settings?.sshPrivateKeyEncrypted) return; // transient config gap, retry next tick

	let conn: Client | undefined;
	try {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		conn = await connect(settings, privateKey);
		const { output } = await execCommand(
			conn,
			`EC=""; [ -f "${build.remoteExitPath}" ] && EC=$(cat "${build.remoteExitPath}"); ` +
				`echo "$EC"; echo "${POLL_SPLIT_MARKER}"; ` +
				`tail -c ${LOG_READ_BYTES} "${build.remoteLogPath}" 2>/dev/null || true`
		);
		const splitIndex = output.indexOf(POLL_SPLIT_MARKER);
		if (splitIndex === -1) return; // unexpected shape, retry next tick

		const exitCodeRaw = output.slice(0, splitIndex).trim();
		const log = output.slice(splitIndex + POLL_SPLIT_MARKER.length).replace(/^\r?\n/, '');

		if (exitCodeRaw === '') {
			// Still running - keep the live-view log fresh, best effort only.
			await db.flatpakBuild
				.update({ where: { id: build.id }, data: { log } })
				.catch((e) => console.error(`Failed to refresh live log for build ${build.id}:`, e));
			return;
		}

		const ok = exitCodeRaw === '0';
		const app = build.flatpakApp;
		// The commit actually built can be later than app.gitLastCommit if more pushes
		// landed between the watcher flagging this for review and the reviewer
		// approving it - record what was really built, not just what was detected.
		const gitCommitMatch =
			ok && app.sourceType === 'GIT' ? log.match(/^FORGE_GIT_COMMIT=(.+)$/m) : null;
		const displayData =
			ok && app.sourceType === 'GIT' ? await updateDisplayDataFromBuildLog(app.id, log) : {};

		try {
			await db.flatpakApp.update({
				where: { id: app.id },
				data: {
					status: ok ? 'APPROVED' : 'FAILED',
					buildFinishedAt: new Date(),
					...(gitCommitMatch ? { gitLastCommit: gitCommitMatch[1].trim() } : {}),
					...displayData
				}
			});
			await db.flatpakBuild.update({
				where: { id: build.id },
				data: { status: ok ? 'SUCCESS' : 'FAILED', log, finishedAt: new Date() }
			});
		} catch (e) {
			console.error(`Failed to finalize build ${build.id}, will retry next tick:`, e);
			return;
		}

		activeBuildIds.delete(build.id);
		await execCommand(conn, `rm -f "${build.remoteLogPath}" "${build.remoteExitPath}"`).catch(
			() => {}
		);

		if (app.submittedById) {
			await notifyUser(
				app.submittedById,
				ok
					? {
							type: 'flatpak_approved',
							title: `${app.name} was published`,
							link: `/dashboard/flatpaks/${app.id}`
						}
					: {
							type: 'flatpak_failed',
							title: `${app.name} failed to build`,
							body: log.slice(-500),
							link: `/dashboard/flatpaks/${app.id}`
						}
			).catch((e) => console.error(`Failed to notify submitter for build ${build.id}:`, e));
		}
	} catch (e) {
		console.error(`Poll failed for build ${buildId}, will retry next tick:`, e);
	} finally {
		conn?.end();
	}
}

let pollerStarted = false;

// Wired from hooks.server.ts next to startGitWatcher, same guard-against-double-
// start shape. Reconciliation runs once at startup so a row left on PROCESSING
// by a crash/restart (or the exact DB-write race this file's poller exists to
// survive) gets picked back up automatically instead of needing a manual retry.
export function startBuildPoller(): void {
	if (pollerStarted) return;
	pollerStarted = true;

	reconcileStuckBuilds().catch((e) => console.error('Build poller reconciliation failed:', e));

	setInterval(async () => {
		for (const buildId of [...activeBuildIds]) {
			await pollBuildOnce(buildId);
		}
	}, POLL_INTERVAL_MS);
}

async function reconcileStuckBuilds(): Promise<void> {
	const stuck = await db.flatpakApp.findMany({ where: { status: 'PROCESSING' } });
	for (const app of stuck) {
		const build = await db.flatpakBuild.findFirst({
			where: { flatpakAppId: app.id, finishedAt: null },
			orderBy: { startedAt: 'desc' }
		});
		if (build) activeBuildIds.add(build.id);
	}
}

async function finalizeLaunchFailure(buildId: string, app: FlatpakApp, log: string): Promise<void> {
	await db.flatpakApp.update({
		where: { id: app.id },
		data: { status: 'FAILED', buildFinishedAt: new Date() }
	});
	await db.flatpakBuild.update({
		where: { id: buildId },
		data: { status: 'FAILED', log, finishedAt: new Date() }
	});
	if (app.submittedById) {
		await notifyUser(app.submittedById, {
			type: 'flatpak_failed',
			title: `${app.name} failed to build`,
			body: log.slice(-500),
			link: `/dashboard/flatpaks/${app.id}`
		}).catch((e) => console.error('Failed to notify submitter of launch failure:', e));
	}
}

// Emergency stop, wired from the Infra Settings admin action: kills whatever's
// actually still running on the remote host (best effort - a session that
// already finished/never existed just no-ops) and marks every PROCESSING
// app/build FAILED. Unlike pollBuildOnce's finalize, this is a deliberate
// synchronous one-off admin action (matches repairAppstream's shape), not
// something retried automatically, so a per-app failure is recorded in the
// returned log and skipped rather than the whole call throwing.
export async function abortAllProcessingBuilds(): Promise<{
	ok: boolean;
	log: string;
	count: number;
}> {
	const apps = await db.flatpakApp.findMany({
		where: { status: 'PROCESSING' },
		include: { builds: { where: { finishedAt: null }, orderBy: { startedAt: 'desc' }, take: 1 } }
	});
	if (apps.length === 0) {
		return { ok: true, log: 'No builds are currently processing.', count: 0 };
	}

	const lines: string[] = [];
	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });

	if (settings?.sshPrivateKeyEncrypted) {
		let conn: Client | undefined;
		try {
			const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
			conn = await connect(settings, privateKey);
			for (const app of apps) {
				const build = app.builds[0];
				if (!build) continue;
				const { output } = await execCommand(
					conn,
					`screen -S "${build.screenSessionName}" -X quit >/dev/null 2>&1; ` +
						`rm -f "${build.remoteLogPath}" "${build.remoteExitPath}"; echo done`
				);
				lines.push(`${app.appid}: session kill attempted (${output.trim() || 'done'})`);
			}
		} catch (e) {
			lines.push(
				`Could not reach the remote host to abort running sessions: ${e instanceof Error ? e.message : String(e)}`
			);
		} finally {
			conn?.end();
		}
	} else {
		lines.push('Infra SSH key not configured - skipped aborting remote sessions.');
	}

	let ok = true;
	for (const app of apps) {
		const build = app.builds[0];
		try {
			if (build) {
				activeBuildIds.delete(build.id);
				await db.flatpakBuild.update({
					where: { id: build.id },
					data: {
						status: 'FAILED',
						log: `${build.log}\n\n[Aborted by an admin via Infra Settings.]`,
						finishedAt: new Date()
					}
				});
			}
			await db.flatpakApp.update({
				where: { id: app.id },
				data: { status: 'FAILED', buildFinishedAt: new Date() }
			});
			if (app.submittedById) {
				await notifyUser(app.submittedById, {
					type: 'flatpak_failed',
					title: `${app.name} failed to build`,
					body: 'The build was aborted by an administrator.',
					link: `/dashboard/flatpaks/${app.id}`
				}).catch((e) =>
					console.error(`Failed to notify submitter for aborted build ${app.id}:`, e)
				);
			}
			lines.push(`${app.appid}: marked FAILED`);
		} catch (e) {
			ok = false;
			lines.push(`${app.appid}: failed to update - ${e instanceof Error ? e.message : String(e)}`);
		}
	}

	return { ok, log: lines.join('\n'), count: apps.length };
}

const triggeringApps = new Set<string>();

// Creates the FlatpakBuild history row, prunes anything past the 10 most recent
// for this app, then launches the build detached (see launchRemoteBuild) and
// hands it off to the shared poller. Doesn't await the build itself completing -
// the caller (the review approve/retry action) returns immediately, same as
// before, but the build's outcome is now tracked durably instead of living only
// in this async call's own stack.
export function triggerPublish(flatpakAppId: string, triggeredById?: string): void {
	if (triggeringApps.has(flatpakAppId)) return;
	triggeringApps.add(flatpakAppId);
	launchPublish(flatpakAppId, triggeredById).finally(() => triggeringApps.delete(flatpakAppId));
}

async function launchPublish(flatpakAppId: string, triggeredById?: string): Promise<void> {
	const app = await db.flatpakApp.findUnique({ where: { id: flatpakAppId } });
	if (!app) return;

	const paths = remoteBuildPaths(app.id);
	const build = await db.flatpakBuild.create({
		data: {
			flatpakAppId: app.id,
			status: 'PROCESSING',
			log: '',
			screenSessionName: paths.sessionName,
			remoteLogPath: paths.logPath,
			remoteExitPath: paths.exitPath,
			triggeredById
		}
	});

	const stale = await db.flatpakBuild.findMany({
		where: { flatpakAppId: app.id },
		orderBy: { startedAt: 'desc' },
		skip: 10,
		select: { id: true }
	});
	if (stale.length) {
		await db.flatpakBuild.deleteMany({ where: { id: { in: stale.map((b) => b.id) } } });
	}

	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (!settings) {
		await finalizeLaunchFailure(build.id, app, 'Infra settings are not configured.');
		return;
	}

	const { ok, log } = await launchRemoteBuild(app, settings, paths);
	if (!ok) {
		await finalizeLaunchFailure(build.id, app, log);
		return;
	}

	activeBuildIds.add(build.id);
}
