import { Client } from 'ssh2';
import sshpk from 'sshpk';
import { XMLParser } from 'fast-xml-parser';
import { env } from '$env/dynamic/private';
import { db } from './db';
import { decryptSecret } from './secrets';
import { notifyUser } from './notifications';
import { uploadFile } from './r2';
import type { FlatpakApp, InfraSettings } from '$lib/generated/prisma/client';

export function generateSshKeypair(): { publicKey: string; privateKeyOpenSsh: string } {
	const key = sshpk.generatePrivateKey('ed25519');
	key.comment = 'forge@blossomos';
	return {
		publicKey: key.toPublic().toString('ssh'),
		privateKeyOpenSsh: key.toString('openssh')
	};
}

// Builds the full remote pipeline as a single self-deleting script. The GPG key ID is
// derived dynamically on the remote host (matching the user's existing tooling) rather
// than stored anywhere. Deliberately does NOT force-delete the appstream2/x86_64 ref
// before regenerating: that's a manual repair step for when the branch is already
// broken, not something to run on every routine publish, doing it unconditionally
// disconnects the ref's history from what existing clients have cached, which can
// surface as a static-delta checksum mismatch on their next pull.
//
// Deliberately does NOT check out the tree and inject/overwrite any metainfo.xml or
// app-info/xmls fragment of its own anymore. That used to be necessary because Forge's
// web form collected name/summary/icon/etc as free text with no relation to what was
// actually inside the bundle, so something had to write real AppStream data into the
// tree. Now that submission (see extractAppstreamMetadata below) reads the bundle's
// OWN real AppStream data instead of asking the developer to retype it, that data is
// already correct and already in the tree from build-import-bundle, overwriting it
// only risked leaving stale, inconsistent leftovers (e.g. a real bundle's own
// `files/share/app-info/icons/flatpak/*` icon cache, generated by the developer's own
// `appstreamcli compose` step, sitting orphaned next to a hand-written xml.gz that no
// longer referenced it) without actually fixing anything. Publishing is now just:
// validate in staging, copy the untouched commit into the shared repo, and let
// build-update-repo compose the aggregate catalog from what's really there.

// Shared by every remote script that needs build scratch space (buildRemoteScript,
// buildExtractScript). Defaults to mktemp's own default TMPDIR, which on some hosts
// sits on a partition too small for a flatpak-builder build or a multi-GB bundle
// download. settings.buildWorkDir lets an admin point that scratch space at a
// larger disk instead. mkdir -p plus set -e means a misconfigured/unwritable path
// fails the script immediately with mkdir's own error, rather than surfacing later
// as an opaque "No space left on device" mid-build.
function buildWorkdirSetup(settings: InfraSettings): string {
	if (!settings.buildWorkDir) return 'WORKDIR=$(mktemp -d)';
	return `mkdir -p "${settings.buildWorkDir}"
WORKDIR=$(mktemp -d -p "${settings.buildWorkDir}")`;
}

// The OSTree repo itself lives in R2, not on the remote host's local disk, so
// every script that touches $REPO_PATH mounts the admin-configured bucket/path
// with rclone first and unmounts it again on the way out (see r2UnmountClause,
// wired into each script's trap). The mount is entirely ephemeral: config is
// passed as env vars for this one rclone invocation, nothing is ever written to
// an rclone.conf on the remote host, and R2_ACCESS_KEY_ID/R2_SECRET_ACCESS_KEY
// are the same credentials Forge's own server already uses for uploads (see
// r2.ts), just pointed at a different bucket. Must run after $WORKDIR exists,
// the mountpoint and rclone's own vfs cache both live under it.
// --vfs-cache-mode writes buffers a file locally until it's closed and then
// uploads it whole, which is what gives ostree's rename-based object writes the
// atomicity object storage can't provide on its own; reads of objects already
// in the bucket still stream straight from R2.
function buildR2MountSetup(settings: InfraSettings): string {
	return `MOUNT_DIR="$WORKDIR/r2-repo"
mkdir -p "$MOUNT_DIR"
RCLONE_CONFIG_R2REPO_TYPE=s3 \\
RCLONE_CONFIG_R2REPO_PROVIDER=Cloudflare \\
RCLONE_CONFIG_R2REPO_ACCESS_KEY_ID="${env.R2_ACCESS_KEY_ID}" \\
RCLONE_CONFIG_R2REPO_SECRET_ACCESS_KEY="${env.R2_SECRET_ACCESS_KEY}" \\
RCLONE_CONFIG_R2REPO_ENDPOINT="https://${env.R2_ACCOUNT_ID}.eu.r2.cloudflarestorage.com" \\
rclone mount "r2repo:${settings.r2BucketName}/${settings.r2RepoPath}" "$MOUNT_DIR" \\
  --daemon --vfs-cache-mode writes --cache-dir="$WORKDIR/rclone-cache"

for i in $(seq 1 30); do
  mountpoint -q "$MOUNT_DIR" && break
  sleep 1
done
mountpoint -q "$MOUNT_DIR" || { echo "R2 repo mount never became ready" >&2; exit 1; }

REPO_PATH="$MOUNT_DIR"
`;
}

// Appended to every trap that calls buildR2MountSetup, and must run before the
// trap's "rm -rf $WORKDIR" (the mountpoint lives under it) - lazy unmount as a
// fallback in case something still has a handle open when the script exits.
function r2UnmountClause(): string {
	return `[ -n "\${MOUNT_DIR:-}" ] && (fusermount -uz "$MOUNT_DIR" 2>/dev/null || umount "$MOUNT_DIR" 2>/dev/null || true)`;
}

// Used by buildRemoteScript (PUBLISH phase) ONLY, in place of
// buildR2MountSetup above - repair/unpublish still use the plain host-side
// rclone mount, unmigrated for now. Instead of Forge running `rclone mount`
// itself, this asks the rclone Docker/Podman volume plugin (`rclone serve
// docker`, registered as a persistent systemd service on this host, socket
// path listed in /etc/containers/containers.conf's [engine.volume_plugins] -
// manual one-time host prerequisite, see README, UNVERIFIED against a real
// Podman install) to create and manage the FUSE mount itself, entirely inside
// its own daemon/namespace, then hands the container a plain named volume
// (`-v "$R2_VOLUME:/repo"` in buildRemoteScript) instead of a bind-mounted
// host path. A fresh, uniquely-named volume per run, destroyed in the trap
// the moment this script exits - same "credentials only exist for the
// duration of one run" posture buildR2MountSetup always had, the plugin's own
// on-disk volume bookkeeping (docker-plugin.state) never holds
// R2_ACCESS_KEY_ID/SECRET for longer than a single publish. Must run with
// `sudo docker` (same rootful Podman as everywhere else in this file, and the
// plugin socket must be registered in ROOT's own containers.conf, not
// buildUser's/remoteUser's per-user one, or `sudo docker volume create` won't
// see it).
function buildR2VolumeSetup(settings: InfraSettings): string {
	return `R2_VOLUME="forge-r2-$(date +%s)-$$"
sudo docker volume create --driver rclone \\
  -o type=s3 \\
  -o path="${settings.r2BucketName}/${settings.r2RepoPath}" \\
  -o s3-provider=Cloudflare \\
  -o s3-access-key-id="${env.R2_ACCESS_KEY_ID}" \\
  -o s3-secret-access-key="${env.R2_SECRET_ACCESS_KEY}" \\
  -o s3-endpoint="https://${env.R2_ACCOUNT_ID}.eu.r2.cloudflarestorage.com" \\
  -o vfs-cache-mode=writes \\
  "$R2_VOLUME"
`;
}

// Mirrors r2UnmountClause above but for buildR2VolumeSetup's plugin-backed
// volume - removing it also tears down the rclone plugin's own FUSE mount for
// it, nothing left running once this exits.
function r2VolumeRemoveClause(): string {
	return `[ -n "\${R2_VOLUME:-}" ] && sudo docker volume rm -f "$R2_VOLUME" 2>/dev/null || true`;
}

// Imports the admin-uploaded signing key fresh on every run and resolves its
// fingerprint straight from the key file itself (via --import-options
// show-only, which doesn't touch the keyring), rather than by listing
// whatever secret keys the remote keyring happens to already have. That
// "just list secret keys and take the first one" approach is what silently
// signed everything with the wrong key once the remote keyring ever held
// more than one - see the incident this replaced. Requires $GPG_PASSPHRASE
// to already be set (each caller reads its own passphrase differently, see
// buildRemoteScript/buildRepairScript/buildUnpublishScript).
function buildGpgImportSection(gpgKeyPath: string): string {
	return `GPG_ID=$(gpg --batch --with-colons --import-options show-only --import "${gpgKeyPath}" 2>/dev/null | awk -F: '/^fpr:/ {print $10; exit}')
if [ -z "$GPG_ID" ]; then
  echo "Could not read a fingerprint from the configured GPG signing key" >&2
  exit 1
fi
gpg --batch --import "${gpgKeyPath}"
KEYGRIP=$(gpg --with-keygrip -K "$GPG_ID" | awk '/Keygrip/ {print $3; exit}')
$(gpgconf --list-dirs libexecdir)/gpg-preset-passphrase --preset "$KEYGRIP" <<< "$GPG_PASSPHRASE"`;
}

// Bundles are self-describing: build-import-bundle always imports under the
// bundle's OWN embedded appid/branch, regardless of what this submission
// declared. Importing straight into $REPO_PATH and only checking the ref
// afterward would leave a real, signed commit sitting in the shared repo on
// a mismatch, nothing ever cleans that up, and every later aggregate
// appstream2 rebuild sweeps it back in. Staging first means a mismatch never
// touches the shared repo at all.
//
// GIT-sourced submissions no longer run flatpak-builder here at all - that
// now happens in isolation on a separate Docker build host (see
// buildContainerScript/buildDockerBuildScript below), which produces an
// unsigned bundle and hands it to this same import path via localBundlePath,
// same as a developer's own direct BUNDLE upload just without the curl. The
// commit hash and metainfo/icon base64 for GIT submissions are extracted
// during that build-host step instead (into their own small sidecar files,
// same reasoning as ever - see pollBuildOnce's LOG_READ_BYTES comment for why
// these can't just be echoed into the combined log).
interface BuildSidecarPaths {
	commitPath: string;
	metainfoPath: string;
	iconPath: string;
	bundlePath: string;
}

// localBundlePath is set only when Forge has already SFTP'd a built bundle to
// this fixed path before launching the script (the GIT case, after the
// Docker build host finishes) - same fixed-path-outside-$WORKDIR convention
// already used for gpgKeyFilePath/passphraseFilePath below. Otherwise (a
// developer's direct BUNDLE upload) this curls app.bundleUrl as before.
function buildBundleImportSection(app: FlatpakApp, localBundlePath?: string): string {
	if (localBundlePath) {
		return `
BUNDLE_PATH="${localBundlePath}"

flatpak build-import-bundle --gpg-sign="$GPG_ID" "$STAGING_REPO" "$BUNDLE_PATH"
`;
	}

	return `
BUNDLE_URL="${app.bundleUrl}"

curl -fsSL "$BUNDLE_URL" -o bundle.flatpak

flatpak build-import-bundle --gpg-sign="$GPG_ID" "$STAGING_REPO" bundle.flatpak
`;
}

// Runs *inside* the Docker container launched by buildDockerBuildScript
// below, against WORKDIR/APPID/MANIFEST_PATH/METAINFO_PATH/ICON_PATH/
// BUNDLE_PATH env vars the outer script passes in. The container is started
// with identity bind mounts (host path == container path for both $WORKDIR
// and /tmp), so every path here is exactly the same absolute path on both
// sides - no host/container path translation needed anywhere. Never touches
// GPG or the shared repo: this only ever produces an UNSIGNED bundle, which
// buildBundleImportSection above imports and signs on the signing host
// afterward. This is deliberately almost identical to the old GIT branch of
// the old single-host GIT build path (see git history), just relocated into the container
// and ending in `flatpak build-bundle` instead of `pull-local` into a shared
// repo - preserve the appid-scoped extraction exactly, it's already been
// fixed through several real production bugs (see flatpak_publish_pipeline
// notes: an unscoped glob previously picked up a bundled QEMU module's own
// qemu.png, or a base Wine app's own name/icon, instead of the submitted
// app's).
function buildContainerScript(): string {
	return `#!/usr/bin/env bash
set -euo pipefail
cd "$WORKDIR"

# --disable-rofiles-fuse: FUSE may not be available/permitted in the
# container, matching the same "don't assume privileged capabilities" lesson
# as ostree checkout's -U flag elsewhere in this file. --state-dir explicitly
# under $WORKDIR avoids flatpak-builder's cache dir landing on a different
# filesystem than the build/target dirs, which it refuses to do.
flatpak-builder --repo=build-repo --state-dir=.flatpak-builder \\
  --force-clean --disable-rofiles-fuse --install-deps-from=flathub \\
  build-dir "src/$MANIFEST_PATH"

REF=$(ostree refs --repo=build-repo | grep "^app/$APPID/" | head -n1 || true)
if [ -z "$REF" ]; then
  # Themes/extensions publish as a runtime rather than an app.
  REF=$(ostree refs --repo=build-repo | grep "^runtime/$APPID/" | head -n1 || true)
fi
if [ -z "$REF" ]; then
  echo "Could not find a matching app or runtime ref for $APPID after building (appid/branch mismatch, or the build didn't produce a ref)" >&2
  exit 1
fi
BRANCH_NAME=$(echo "$REF" | cut -d/ -f4)

BUNDLE_EXTRA_ARGS=()
case "$REF" in
  runtime/*) BUNDLE_EXTRA_ARGS+=(--runtime) ;;
esac
flatpak build-bundle "\${BUNDLE_EXTRA_ARGS[@]}" build-repo "$BUNDLE_PATH" "$APPID" "$BRANCH_NAME"

ostree checkout -U --repo=build-repo "$REF" post-build-checkout
# Named exactly $APPID, never a bare '*.xml'/'*.png' glob: a git build's tree
# isn't just the submitted app, it's also whatever base app/SDK
# extension/module the manifest pulled in (e.g. org.winehq.Wine as a base, or
# a bundled qemu module), and those ship their own metainfo/icon files in the
# exact same directories.
METAINFO_SRC=$(find post-build-checkout/files/share/metainfo post-build-checkout/export/share/metainfo -maxdepth 1 \\( -name "$APPID.metainfo.xml" -o -name "$APPID.appdata.xml" \\) 2>/dev/null | head -n1 || true)
if [ -n "$METAINFO_SRC" ]; then
  base64 -w0 "$METAINFO_SRC" > "$METAINFO_PATH"
fi
# Sized PNGs first, then scalable/apps as a fallback: some manifests only
# ship an svg there (no raster icon at all), and some mistakenly install a
# raster png into scalable/apps instead of a proper sized directory.
ICON_SRC=$(ls post-build-checkout/files/share/icons/hicolor/256x256/apps/"$APPID".png \\
  post-build-checkout/files/share/icons/hicolor/128x128/apps/"$APPID".png \\
  post-build-checkout/files/share/icons/hicolor/64x64/apps/"$APPID".png \\
  post-build-checkout/files/share/icons/hicolor/48x48/apps/"$APPID".png \\
  post-build-checkout/files/share/icons/hicolor/scalable/apps/"$APPID".svg \\
  post-build-checkout/files/share/icons/hicolor/scalable/apps/"$APPID".png 2>/dev/null | head -n1 || true)
if [ -n "$ICON_SRC" ]; then
  base64 -w0 "$ICON_SRC" > "$ICON_PATH"
fi
`;
}

// The outer script that actually runs on the build host (never inside the
// container) via the same detached `screen -dmS` mechanism the signing
// host's script already uses - see launchDetachedScript. A real Docker build
// can run just as long as flatpak-builder always could, so it gets the same
// survives-a-restart treatment. Never imports the GPG key or mounts the R2
// repo: this host only ever produces an unsigned bundle, nothing here needs
// signing-host credentials.
function buildDockerBuildScript(
	app: FlatpakApp,
	settings: InfraSettings,
	sidecar: BuildSidecarPaths,
	containerScriptPath: string
): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0" "${containerScriptPath}"; [ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

APPID="${app.appid}"
GIT_URL="${app.gitUrl}"
GIT_BRANCH="${app.gitBranch}"
MANIFEST_PATH="${app.gitManifestPath}"

${buildWorkdirSetup(settings)}
cd "$WORKDIR"

git clone --recurse-submodules --branch "$GIT_BRANCH" --depth 1 "$GIT_URL" src
git -C src rev-parse HEAD > "${sidecar.commitPath}"

# sudo + rootful podman, not the plain rootless \`docker\` (Podman's docker-shim)
# buildUser normally has: rootless Podman remaps container root onto an
# unprivileged subordinate UID from /etc/subuid no matter what
# capabilities/--privileged are added, so it can never actually access the
# bind-mounted $WORKDIR (owned by buildUser's own real UID, created by the
# mktemp above) - this is what produced \`Can't find source path
# .../build-dir/files: Permission denied\` from bwrap. Rootful podman's
# container root IS real host root, same as the pipeline's original
# pre-Docker-isolation design, so --privileged actually means something and
# none of the rootless UID-mapping problems apply. Requires buildUser to have
# passwordless sudo for podman (see README), and the image to be pulled/built
# into root's OWN podman storage (/var/lib/containers) separately from
# whatever's in buildUser's rootless storage (~/.local/share/containers) -
# the two are entirely separate stores, this never touches buildUser's own
# rootless images/containers. Identity bind mounts ($WORKDIR and /tmp map to
# the same path inside the container) so buildContainerScript can share these
# exact paths with no translation.
sudo docker run --rm \\
  --privileged \\
  -v "$WORKDIR:$WORKDIR" \\
  -v /tmp:/tmp \\
  -w "$WORKDIR" \\
  -e WORKDIR="$WORKDIR" \\
  -e APPID="$APPID" \\
  -e MANIFEST_PATH="$MANIFEST_PATH" \\
  -e METAINFO_PATH="${sidecar.metainfoPath}" \\
  -e ICON_PATH="${sidecar.iconPath}" \\
  -e BUNDLE_PATH="${sidecar.bundlePath}" \\
  "${settings.buildDockerImage}" \\
  bash "${containerScriptPath}"

echo "FORGE_BUILD_OK"
`;
}

// Runs *inside* the Docker container launched by buildRemoteScript below,
// against WORKDIR/REPO_PATH/APPID/GPG_KEY_PATH/GPG_PASSPHRASE_PATH env vars
// the outer script passes in. $REPO_PATH (the outer script's R2 volume) is
// mounted in under /repo - see buildR2VolumeSetup.
//
// $STAGING_REPO and /work (the bundle-download scratch dir for the
// direct-BUNDLE curl case) are both --tmpfs mounts (see buildRemoteScript's
// docker run) - this took three attempts to land on (2026-08-07), all
// against the same reproduced `error: Importing <hash>.commit: renameat:
// Operation not permitted` from `flatpak build-import-bundle`: (1) running
// this on a bind-mounted $WORKDIR under a privileged/rootful container - no
// change, since a bind mount doesn't alter the underlying filesystem, it was
// still whatever the signing host's own storage was doing; (2) moving
// $STAGING_REPO to a plain container-native path (no bind mount at all,
// pure container filesystem) - STILL no change, which was the real tell:
// every combination of privilege and mount strategy we tried produced the
// byte-identical error, meaning this was never a container/privilege/mount
// issue at all - containers still make the actual renameat() syscall through
// the *host kernel*, so if the underlying storage backing either the host's
// own paths or the container engine's own storage root is NFS (which this
// specific error is a well-documented symptom of - NFS doesn't support the
// atomic rename OSTree uses to commit objects), nothing about how a
// container is invoked was ever going to matter. (3) actual fix: force
// $STAGING_REPO and /work onto tmpfs specifically, an in-RAM filesystem with
// real POSIX rename semantics, sidestepping whatever the container engine's
// default storage backend is doing entirely rather than hoping it isn't NFS.
// Tmpfs size deliberately left uncapped (defaults to a fraction of host RAM)
// rather than guessing a limit - an unusually large bundle (see the
// bundled-QEMU example elsewhere in this file) could need capping this
// explicitly with --tmpfs /staging-repo:size=... if it ever OOMs.
//
// GPG import + preset-passphrase happen in here too now rather than on the
// host, since gpg-agent needs to be reachable for both that step and the
// later --gpg-sign, and this container's lifetime spans both - see the
// shared image's baked-in allow-preset-passphrase (was previously a manual
// one-time host prerequisite, now obsolete: every run gets a fresh
// disposable keyring/agent from the image, nothing to configure or reload on
// the host anymore).
function buildPublishContainerScript(app: FlatpakApp, localBundlePath?: string): string {
	return `#!/usr/bin/env bash
set -euo pipefail
cd /work

GPG_PASSPHRASE=$(cat "$GPG_PASSPHRASE_PATH")
APPID="${app.appid}"

${buildGpgImportSection('$GPG_KEY_PATH')}

STAGING_REPO="/staging-repo"
ostree init --repo="$STAGING_REPO" --mode=archive-z2

${buildBundleImportSection(app, localBundlePath)}

REF=$(ostree refs --repo="$STAGING_REPO" | grep "^app/$APPID/" | head -n1)
if [ -z "$REF" ]; then
  # Themes/extensions publish as a runtime rather than an app, see extractAppstreamMetadata.
  REF=$(ostree refs --repo="$STAGING_REPO" | grep "^runtime/$APPID/" | head -n1)
fi
if [ -z "$REF" ]; then
  echo "Could not find a matching app or runtime ref for $APPID after building (appid/branch mismatch, or the build didn't produce a ref) - refusing to publish to the shared repo" >&2
  exit 1
fi

ostree pull-local --repo="$REPO_PATH" "$STAGING_REPO" "$REF"

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"
`;
}

// passphraseFilePath: unlike buildRepairScript/buildUnpublishScript (still piped
// over exec's stdin, see execScript), this script runs detached inside a `screen`
// session with no interactive stdin to receive anything - the passphrase has to
// arrive as a file instead. Deleted via the trap the moment it's read, same
// self-deleting treatment the script already gives itself.
//
// localBundlePath (see buildBundleImportSection) is also cleaned up by the
// trap when present - it's a file Forge SFTP'd in ahead of time to a fixed
// path under /tmp, same as the passphrase/GPG key files.
//
// R2 is no longer bind-mounted from a host-side `rclone mount` at all - see
// buildR2VolumeSetup above for why (a bind mount doesn't isolate anything
// from whatever the host filesystem itself is doing, same lesson the
// $STAGING_REPO fix above already taught the hard way). Instead the rclone
// Docker/Podman volume plugin creates+owns the FUSE mount entirely inside its
// own daemon, and the container just gets a plain named volume
// (`-v "$R2_VOLUME:/repo"`) - no host path, no bind mount, no identity-mount
// path-matching to keep in sync between outer/inner scripts. This also means
// this script has no more use for $WORKDIR at all (nothing it does touches
// the host filesystem anymore), so unlike buildDockerBuildScript on the build
// host, there's no workdir setup or bind mount of one here.
// `sudo docker run --privileged`: same reasoning as buildDockerBuildScript on
// the build host - this account's `docker` is rootless Podman, which remaps
// container root onto an unprivileged subordinate UID no matter what
// capabilities/--privileged are added, so it can never access resources it
// doesn't own. Rootful Podman via sudo makes container root real host root
// instead, avoiding that whole class of problem. Same image as the build
// host (settings.buildDockerImage) - one Dockerfile serves both purposes.
function buildRemoteScript(
	app: FlatpakApp,
	settings: InfraSettings,
	passphraseFilePath: string,
	gpgKeyFilePath: string,
	containerScriptPath: string,
	localBundlePath?: string
): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0" "${containerScriptPath}" "${passphraseFilePath}" "${gpgKeyFilePath}"${localBundlePath ? ` "${localBundlePath}"` : ''}; ${r2VolumeRemoveClause()}' EXIT

${buildR2VolumeSetup(settings)}

sudo docker run --rm \\
  --privileged \\
  --tmpfs /staging-repo \\
  --tmpfs /work \\
  -v "$R2_VOLUME:/repo" \\
  -v /tmp:/tmp \\
  -e REPO_PATH=/repo \\
  -e APPID="${app.appid}" \\
  -e GPG_KEY_PATH="${gpgKeyFilePath}" \\
  -e GPG_PASSPHRASE_PATH="${passphraseFilePath}" \\
  "${settings.buildDockerImage}" \\
  bash "${containerScriptPath}"

echo "FORGE_PUBLISH_OK"
`;
}

function sftpWriteFile(
	conn: Client,
	remotePath: string,
	contents: string,
	mode = 0o700
): Promise<void> {
	return new Promise((resolve, reject) => {
		conn.sftp((err, sftp) => {
			if (err) return reject(err);
			sftp.writeFile(remotePath, contents, { mode }, (writeErr) => {
				if (writeErr) return reject(writeErr);
				resolve();
			});
		});
	});
}

// Like execScript, but for commands that don't need a piped stdin (the launch and
// poll steps of the detached-build flow below never pipe the GPG passphrase over
// exec - see buildRemoteScript's passphraseFilePath for why).
function execCommand(conn: Client, command: string): Promise<{ exitCode: number; output: string }> {
	return new Promise((resolve, reject) => {
		conn.exec(command, (err, stream) => {
			if (err) return reject(err);
			let output = '';
			stream.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8');
			});
			stream.stderr.on('data', (chunk: Buffer) => {
				output += chunk.toString('utf8');
			});
			stream.on('close', (exitCode: number) => {
				resolve({ exitCode: exitCode ?? 1, output });
			});
			stream.on('error', reject);
		});
	});
}

function execScript(
	conn: Client,
	remotePath: string,
	gpgPassphrase: string
): Promise<{ exitCode: number; log: string }> {
	return new Promise((resolve, reject) => {
		conn.exec(`bash ${remotePath}`, (err, stream) => {
			if (err) return reject(err);
			let log = '';
			stream.on('data', (chunk: Buffer) => {
				log += chunk.toString('utf8');
			});
			stream.stderr.on('data', (chunk: Buffer) => {
				log += chunk.toString('utf8');
			});
			stream.on('close', (exitCode: number) => {
				resolve({ exitCode: exitCode ?? 1, log });
			});
			stream.on('error', reject);
			stream.end(`${gpgPassphrase}\n`);
		});
	});
}

// Parameterized by which host/user to reach rather than always reading
// settings.remoteHost/remoteUser, so this same helper serves both the
// signing host and the separate Docker build host (see ConnectTarget).
interface ConnectTarget {
	host: string;
	user: string;
}

function signingHostTarget(settings: InfraSettings): ConnectTarget {
	return { host: settings.remoteHost, user: settings.remoteUser };
}

function connect(target: ConnectTarget, privateKey: string): Promise<Client> {
	return new Promise((resolve, reject) => {
		const conn = new Client();
		conn.on('ready', () => resolve(conn));
		conn.on('error', reject);
		conn.connect({
			host: target.host,
			username: target.user,
			privateKey
		});
	});
}

// Manual, explicitly-triggered repair for when the appstream2/x86_64 branch is
// already broken/stale, not run automatically as part of routine publishing
// (see buildRemoteScript's comment for why that caused real corruption once).
function buildRepairScript(settings: InfraSettings, gpgKeyPath: string): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0" "${gpgKeyPath}"; ${r2UnmountClause()}; [ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

IFS= read -r GPG_PASSPHRASE

${buildWorkdirSetup(settings)}

${buildGpgImportSection(gpgKeyPath)}

${buildR2MountSetup(settings)}

ostree refs --repo="$REPO_PATH" appstream2/x86_64 --delete || true

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"

echo "FORGE_REPAIR_OK"
`;
}

// Shared by repairAppstream/unpublishFlatpak/runPublish: loads infra settings, connects,
// writes the given script over SFTP, runs it with the passphrase piped over stdin, and
// always tears the connection down. Never throws, callers get {ok, log} either way.
async function runOnRemote(
	scriptBuilder: (settings: InfraSettings, gpgKeyPath: string) => string,
	remotePathPrefix: string
): Promise<{ ok: boolean; exitCode: number | null; log: string }> {
	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (
		!settings?.sshPrivateKeyEncrypted ||
		!settings.gpgPrivateKeyEncrypted ||
		!settings.gpgPassphraseEncrypted
	) {
		return {
			ok: false,
			exitCode: null,
			log: 'Infra settings are not fully configured (missing SSH key, GPG key, or GPG passphrase).'
		};
	}

	let conn: Client | undefined;
	try {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		const gpgKey = decryptSecret(settings.gpgPrivateKeyEncrypted);
		const gpgPassphrase = decryptSecret(settings.gpgPassphraseEncrypted);
		const remotePath = `${remotePathPrefix}-${Date.now()}.sh`;
		const gpgKeyPath = `${remotePath}.gpgkey`;
		const script = scriptBuilder(settings, gpgKeyPath);

		conn = await connect(signingHostTarget(settings), privateKey);
		await sftpWriteFile(conn, gpgKeyPath, gpgKey, 0o600);
		await sftpWriteFile(conn, remotePath, script);
		const { exitCode, log } = await execScript(conn, remotePath, gpgPassphrase);
		return { ok: exitCode === 0, exitCode, log };
	} catch (e) {
		return { ok: false, exitCode: null, log: e instanceof Error ? e.message : String(e) };
	} finally {
		conn?.end();
	}
}

export async function repairAppstream(): Promise<{ ok: boolean; log: string }> {
	return runOnRemote(buildRepairScript, '/tmp/forge-repair');
}

const EXTRACT_METAINFO_START = 'FORGE_METAINFO_B64_START';
const EXTRACT_METAINFO_END = 'FORGE_METAINFO_B64_END';
const EXTRACT_ICON_START = 'FORGE_ICON_B64_START';
const EXTRACT_ICON_END = 'FORGE_ICON_B64_END';

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

// The extraction scripts now fall back to hicolor/scalable/apps/$APPID.svg
// when no sized raster icon exists, so an extracted icon is no longer
// guaranteed to be a PNG, callers must not assume the extension/mime type.
export function iconFileExtension(buffer: Buffer): 'png' | 'svg' {
	return buffer.subarray(0, 4).equals(PNG_MAGIC) ? 'png' : 'svg';
}

// Read-only: imports the bundle into a throwaway staging repo (never touches the
// shared repo) purely to read back its own, real AppStream metainfo.xml and icon, so
// Forge's web UI can be populated from what's actually inside the bundle instead of
// free-text form fields a developer could type anything into.
function buildExtractScript(bundleUrl: string, settings: InfraSettings): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap '[ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

BUNDLE_URL="${bundleUrl}"

${buildWorkdirSetup(settings)}
cd "$WORKDIR"

echo "FORGE_STEP: downloading bundle"
curl -fsSL "$BUNDLE_URL" -o bundle.flatpak

STAGING_REPO="$WORKDIR/staging-repo"
echo "FORGE_STEP: initializing staging repo"
ostree init --repo="$STAGING_REPO" --mode=archive-z2
echo "FORGE_STEP: importing bundle"
flatpak build-import-bundle "$STAGING_REPO" bundle.flatpak

echo "FORGE_STEP: resolving ref"
# grep exits non-zero when a bundle has no app/ ref at all (e.g. a runtime-only
# bundle, see below), which under set -e -o pipefail would otherwise kill the
# whole script right here before the runtime fallback ever runs.
REF=$(ostree refs --repo="$STAGING_REPO" | grep "^app/" | head -n1 || true)
if [ -z "$REF" ]; then
  # Not every submission is a user-facing app, GTK/Qt themes and other extensions
  # ship as a runtime instead, those have no .desktop file or per-app metainfo.xml,
  # but are still a legitimate thing to host, so accept them too.
  REF=$(ostree refs --repo="$STAGING_REPO" | grep "^runtime/" | head -n1 || true)
fi
if [ -z "$REF" ]; then
  echo "Uploaded file has no importable Flatpak app or runtime ref" >&2
  exit 1
fi
APPID=$(echo "$REF" | cut -d/ -f2)
echo "FORGE_APPID=$APPID"
echo "FORGE_REF=$REF"

echo "FORGE_STEP: checking out ref"
ostree checkout -U --repo="$STAGING_REPO" "$REF" checkout

# metainfo.xml is optional, a runtime typically doesn't ship one, missing metainfo
# just means the name/summary/description/icon fall back to placeholders below
# rather than blocking the submission entirely.
echo "FORGE_STEP: looking for metainfo.xml"
# Named exactly $APPID, not a bare '*.xml' glob, same reasoning as the git
# build path below: a base app/SDK extension baked into the bundle can ship
# its own metainfo/icon in the same directories as the submitted app's own.
METAINFO_PATH=$(find checkout/files/share/metainfo checkout/export/share/metainfo -maxdepth 1 \\( -name "$APPID.metainfo.xml" -o -name "$APPID.appdata.xml" \\) 2>/dev/null | head -n1 || true)
if [ -n "$METAINFO_PATH" ]; then
  echo "${EXTRACT_METAINFO_START}"
  base64 -w0 "$METAINFO_PATH"
  echo ""
  echo "${EXTRACT_METAINFO_END}"
fi

echo "FORGE_STEP: looking for an icon"
# Sized PNGs first, then scalable/apps as a fallback (svg-only icon, or a
# raster png mistakenly installed into scalable/apps instead of a sized dir).
ICON_PATH=$(ls checkout/files/share/icons/hicolor/256x256/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/128x128/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/64x64/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/48x48/apps/"$APPID".png \\
  checkout/files/share/icons/hicolor/scalable/apps/"$APPID".svg \\
  checkout/files/share/icons/hicolor/scalable/apps/"$APPID".png 2>/dev/null | head -n1 || true)
if [ -n "$ICON_PATH" ]; then
  echo "${EXTRACT_ICON_START}"
  base64 -w0 "$ICON_PATH"
  echo ""
  echo "${EXTRACT_ICON_END}"
fi

echo "FORGE_EXTRACT_OK"
`;
}

function extractBetweenMarkers(
	log: string,
	startMarker: string,
	endMarker: string
): string | undefined {
	const start = log.indexOf(startMarker);
	if (start === -1) return undefined;
	const contentStart = start + startMarker.length;
	const end = log.indexOf(endMarker, contentStart);
	if (end === -1) return undefined;
	return log.slice(contentStart, end).trim();
}

// AppStream allows both the older <developer_name> and the newer <developer><name>
// form, and either can appear as a plain string or as an object with a #text node
// depending on whether the parser sees attributes alongside it. A translated
// component (multiple <name>/<summary> elements with different xml:lang) parses
// to an ARRAY of those, which is also `typeof === 'object'` but has no '#text' of
// its own - without this branch every one of these fields silently came back
// empty for any bundle with translated AppStream metadata.
function textOf(value: unknown): string {
	if (typeof value === 'string') return value;
	if (Array.isArray(value)) {
		// Prefer the untranslated/default entry (no xml:lang) for single-value
		// fields, these aren't meant to be localized themselves.
		const untranslated = value.find(
			(v) => typeof v === 'string' || !('@_xml:lang' in (v as Record<string, unknown>))
		);
		return textOf(untranslated ?? value[0]);
	}
	if (value && typeof value === 'object' && '#text' in (value as Record<string, unknown>)) {
		return String((value as Record<string, unknown>)['#text'] ?? '');
	}
	return '';
}

export type LocalizedMetadata = { name: string; summary: string; description: string };

function collectLangVariants(value: unknown): Record<string, string> {
	const items = Array.isArray(value) ? value : value !== undefined && value !== null ? [value] : [];
	const result: Record<string, string> = {};
	for (const item of items) {
		if (typeof item === 'string') {
			if (item.trim()) result.en = item.trim();
			continue;
		}
		if (item && typeof item === 'object') {
			const obj = item as Record<string, unknown>;
			const lang = typeof obj['@_xml:lang'] === 'string' ? (obj['@_xml:lang'] as string) : 'en';
			const text = textOf(obj).trim();
			if (text) result[lang] = text;
		}
	}
	return result;
}

// <description> blocks carry their own inner markup verbatim (see the comment
// on the single-value extraction below), so translated variants are pulled the
// same way, by matching each <description>/<description xml:lang="..."> block
// directly out of the source XML rather than the parsed object tree.
function collectDescriptionVariants(xml: string): Record<string, string> {
	const result: Record<string, string> = {};
	const regex = /<description(?:\s+xml:lang="([^"]+)")?\s*>([\s\S]*?)<\/description>/g;
	let match: RegExpExecArray | null;
	while ((match = regex.exec(xml))) {
		const lang = match[1] || 'en';
		const text = match[2].trim();
		if (text) result[lang] = text;
	}
	return result;
}

// Preview-only: the real submission fields (parseAppstreamComponent, used for
// what's actually saved) are intentionally single-language, Flatpak has no
// translation model the way PwaTranslation exists for PWAs. This just surfaces
// every language actually present in the bundle's own metainfo.xml so a
// submitter can double check translated listings before submitting.
export function parseAppstreamTranslations(xml: string): Record<string, LocalizedMetadata> {
	const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });
	const doc = parser.parse(xml) as Record<string, unknown>;
	const component = (doc.component ?? {}) as Record<string, unknown>;

	const names = collectLangVariants(component.name);
	const summaries = collectLangVariants(component.summary);
	const descriptions = collectDescriptionVariants(xml);

	const langs = new Set([
		...Object.keys(names),
		...Object.keys(summaries),
		...Object.keys(descriptions)
	]);
	if (langs.size === 0) langs.add('en');

	const result: Record<string, LocalizedMetadata> = {};
	for (const lang of langs) {
		result[lang] = {
			name: names[lang] ?? names.en ?? '',
			summary: summaries[lang] ?? summaries.en ?? '',
			description: descriptions[lang] ?? descriptions.en ?? ''
		};
	}
	return result;
}

function parseAppstreamComponent(xml: string): {
	name: string;
	summary: string;
	description: string;
	developerName: string;
	homepageUrl: string;
	screenshots: string[];
} {
	const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });
	const doc = parser.parse(xml) as Record<string, unknown>;
	const component = (doc.component ?? {}) as Record<string, unknown>;

	const name = textOf(component.name).trim();
	const summary = textOf(component.summary).trim();

	// Description is a mix of <p>/<ul>/<ol>/<li> elements meant to be shown as HTML
	// (matches Forge's existing "Description (HTML)" field), pulling the raw inner
	// XML straight out of the source string preserves that markup exactly, rather
	// than trying to reconstruct it from the parsed object tree.
	const descMatch = xml.match(/<description>([\s\S]*?)<\/description>/);
	const description = descMatch ? descMatch[1].trim() : '';

	let developerName = textOf(component.developer_name).trim();
	if (!developerName && component.developer && typeof component.developer === 'object') {
		developerName = textOf((component.developer as Record<string, unknown>).name).trim();
	}

	let homepageUrl = '';
	const urlsRaw = component.url;
	const urls = Array.isArray(urlsRaw) ? urlsRaw : urlsRaw ? [urlsRaw] : [];
	for (const u of urls as Record<string, unknown>[]) {
		if (u?.['@_type'] === 'homepage') homepageUrl = textOf(u).trim();
	}

	const screenshots: string[] = [];
	const shotsRaw = (component.screenshots as Record<string, unknown> | undefined)?.screenshot;
	const shots = Array.isArray(shotsRaw) ? shotsRaw : shotsRaw ? [shotsRaw] : [];
	for (const s of shots as Record<string, unknown>[]) {
		const url = textOf(s?.image).trim();
		if (url) screenshots.push(url);
	}

	return { name, summary, description, developerName, homepageUrl, screenshots };
}

export type ExtractedAppstream = {
	ok: boolean;
	appid?: string;
	branch?: string;
	name?: string;
	summary?: string;
	description?: string;
	developerName?: string;
	homepageUrl?: string;
	screenshots?: string[];
	iconBuffer?: Buffer;
	translations?: Record<string, LocalizedMetadata>;
	error?: string;
	log?: string;
};

export async function extractAppstreamMetadata(bundleUrl: string): Promise<ExtractedAppstream> {
	const { ok, exitCode, log } = await runOnRemote(
		(settings) => buildExtractScript(bundleUrl, settings),
		'/tmp/forge-extract'
	);
	if (!ok || !log.includes('FORGE_EXTRACT_OK')) {
		// The last line isn't necessarily the actual failure, a step can print a
		// perfectly normal progress message and then die with no further output at
		// all (connection drop, remote process killed, out of disk, etc.), so the
		// headline names the last step reached instead of guessing at an error
		// line, the full log (always returned below) has the real detail.
		const lastStepMatch = [...log.matchAll(/^FORGE_STEP: (.+)$/gm)].pop();
		const lastStep = lastStepMatch?.[1];
		const codeDesc =
			exitCode === null ? 'the connection to the signing host failed' : `exit code ${exitCode}`;
		return {
			ok: false,
			error: lastStep
				? `Extraction failed after "${lastStep}" (${codeDesc}) - see log below`
				: `Extraction failed (${codeDesc}) - see log below`,
			log
		};
	}

	const appidMatch = log.match(/^FORGE_APPID=(.+)$/m);
	const refMatch = log.match(/^FORGE_REF=(.+)$/m);
	const metainfoB64 = extractBetweenMarkers(
		log,
		EXTRACT_METAINFO_START,
		EXTRACT_METAINFO_END
	)?.replace(/\s+/g, '');
	const iconB64 = extractBetweenMarkers(log, EXTRACT_ICON_START, EXTRACT_ICON_END)?.replace(
		/\s+/g,
		''
	);

	if (!appidMatch) {
		return { ok: false, error: 'Could not determine an app id for the uploaded bundle', log };
	}

	const appid = appidMatch[1].trim();
	const branch = refMatch ? refMatch[1].trim().split('/').pop() : 'stable';
	const iconBuffer = iconB64 ? Buffer.from(iconB64, 'base64') : undefined;
	const metainfoXml = metainfoB64 ? Buffer.from(metainfoB64, 'base64').toString('utf8') : undefined;
	const parsed = metainfoXml
		? parseAppstreamComponent(metainfoXml)
		: {
				name: '',
				summary: '',
				description: '',
				developerName: '',
				homepageUrl: '',
				screenshots: []
			};
	const translations = metainfoXml ? parseAppstreamTranslations(metainfoXml) : undefined;

	return { ok: true, appid, branch, iconBuffer, translations, log, ...parsed };
}

// Removes a specific app's ref from the repo (if present) and republishes, so the
// repo's summary/deltas/appstream catalog no longer advertise it. Used both by a
// reviewer's explicit "pull" and by deleting a Flatpak that's currently live.
function buildUnpublishScript(
	app: FlatpakApp,
	settings: InfraSettings,
	gpgKeyPath: string
): string {
	return `#!/usr/bin/env bash
set -euo pipefail
trap 'rm -f "$0" "${gpgKeyPath}"; ${r2UnmountClause()}; [ -n "\${WORKDIR:-}" ] && rm -rf "$WORKDIR"' EXIT

IFS= read -r GPG_PASSPHRASE

APPID="${app.appid}"

${buildWorkdirSetup(settings)}

${buildGpgImportSection(gpgKeyPath)}

${buildR2MountSetup(settings)}

REF=$(ostree refs --repo="$REPO_PATH" | grep "^app/$APPID/" | head -n1)
if [ -n "$REF" ]; then
  ostree refs --repo="$REPO_PATH" "$REF" --delete
fi

flatpak build-update-repo \\
  --gpg-sign="$GPG_ID" \\
  --prune \\
  --generate-static-deltas \\
  --verbose \\
  "$REPO_PATH"

echo "FORGE_UNPUBLISH_OK"
`;
}

export async function unpublishFlatpak(app: FlatpakApp): Promise<{ ok: boolean; log: string }> {
	return runOnRemote(
		(settings, gpgKeyPath) => buildUnpublishScript(app, settings, gpgKeyPath),
		`/tmp/forge-unpublish-${app.id}`
	);
}

// Only relevant for GIT-sourced apps: a bundle submission already extracted its
// display data once at upload time (see extractAppstreamMetadata), but a git
// submission has nothing to show until a build actually produces AppStream data,
// so it's re-read from the sidecar files a successful BUILD-phase run wrote
// (see buildContainerScript and BuildSidecarPaths) instead, at the BUILD ->
// PUBLISH handoff in pollBuildOnce.
async function updateDisplayDataFromSidecars(
	metainfoB64: string,
	iconB64: string
): Promise<Record<string, unknown>> {
	const data: Record<string, unknown> = {};

	// Independent of the icon below: a build can produce one without the other
	// (or vice versa), neither should block the other from updating.
	if (metainfoB64) {
		const metainfoXml = Buffer.from(metainfoB64, 'base64').toString('utf8');
		const parsed = parseAppstreamComponent(metainfoXml);
		data.name = parsed.name || undefined;
		data.summary = parsed.summary || undefined;
		data.description = parsed.description || undefined;
		data.homepageUrl = parsed.homepageUrl || undefined;
		data.screenshots = parsed.screenshots.length ? parsed.screenshots : undefined;
	}

	if (iconB64) {
		const iconBuffer = Buffer.from(iconB64, 'base64');
		const iconArrayBuffer = iconBuffer.buffer.slice(
			iconBuffer.byteOffset,
			iconBuffer.byteOffset + iconBuffer.byteLength
		) as ArrayBuffer;
		data.iconUrl = await uploadFile(
			iconArrayBuffer,
			`${crypto.randomUUID()}.${iconFileExtension(iconBuffer)}`
		);
	}

	return Object.fromEntries(Object.entries(data).filter(([, v]) => v !== undefined));
}

// Bounded tail read for both the live-view refresh and the final stored log -
// generous enough for any real build, matches the "read a bounded amount"
// posture already used elsewhere in this file (e.g. notification bodies).
const LOG_READ_BYTES = 5_000_000;
const POLL_SPLIT_MARKER = '__FORGE_POLL_SPLIT__';
const POLL_INTERVAL_MS = 7_000;

interface RemoteBuildPaths extends BuildSidecarPaths {
	scriptPath: string;
	containerScriptPath: string;
	logPath: string;
	exitPath: string;
	passphrasePath: string;
	gpgKeyPath: string;
	sessionName: string;
}

// Sidecar paths are derived from logPath with a fixed suffix scheme so
// pollBuildOnce/abortAllProcessingBuilds can re-derive the exact same paths
// later from just the remoteLogPath already persisted on the FlatpakBuild row,
// no extra columns needed.
function sidecarPathsFromLogPath(logPath: string): BuildSidecarPaths {
	const base = logPath.slice(0, -'.log'.length);
	return {
		commitPath: `${base}.commit`,
		metainfoPath: `${base}.metainfo.b64`,
		iconPath: `${base}.icon.b64`,
		bundlePath: `${base}.flatpak`
	};
}

// Called once per phase (BUILD and, for GIT apps, again for the PUBLISH
// handoff) - each call mints a fresh timestamp-suffixed base, so reusing it
// for a second phase on a different host never collides with the first.
function remoteBuildPaths(appId: string): RemoteBuildPaths {
	const base = `/tmp/forge-publish-${appId}-${Date.now()}`;
	const logPath = `${base}.log`;
	return {
		scriptPath: `${base}.sh`,
		containerScriptPath: `${base}.container.sh`,
		logPath,
		exitPath: `${base}.exit`,
		passphrasePath: `${base}.pass`,
		gpgKeyPath: `${base}.gpgkey`,
		sessionName: `forge-build-${appId}-${Date.now()}`,
		...sidecarPathsFromLogPath(logPath)
	};
}

// Shared by both the build-host and signing-host launches: writes the given
// already-built script (plus any extra small files it needs, e.g. a GPG
// passphrase or the in-container script) and launches it detached inside a
// `screen` session, returning as soon as that launch itself completes
// (near-instant, `-dm` never attaches). The script keeps running on its host
// independent of this SSH connection, this Node process, or Forge restarting
// - see pollBuildOnce for how its outcome is picked back up. Requires
// `screen` on the host (same "assume it's already there" posture as
// flatpak-builder/docker/gpg/git elsewhere in this file). Note: a host with
// systemd-logind's KillUserProcesses=yes will kill a detached screen session
// on SSH logout same as any other process - if builds still die on
// disconnect, `loginctl enable-linger <user>` is the fix.
async function launchDetachedScript(
	target: ConnectTarget,
	privateKey: string,
	scriptPath: string,
	script: string,
	sessionName: string,
	logPath: string,
	exitPath: string,
	extraFiles: { path: string; contents: string; mode?: number }[] = []
): Promise<{ ok: boolean; log: string }> {
	let conn: Client | undefined;
	try {
		conn = await connect(target, privateKey);
		await sftpWriteFile(conn, scriptPath, script);
		for (const f of extraFiles) {
			await sftpWriteFile(conn, f.path, f.contents, f.mode ?? 0o600);
		}

		const launchCommand = `screen -dmS "${sessionName}" bash -c 'bash "${scriptPath}" > "${logPath}" 2>&1; echo $? > "${exitPath}"'`;
		const { exitCode, output } = await execCommand(conn, launchCommand);
		if (exitCode !== 0) {
			return {
				ok: false,
				log: `Failed to launch detached build (screen exited ${exitCode}): ${output}`
			};
		}
		return { ok: true, log: '' };
	} catch (e) {
		return { ok: false, log: e instanceof Error ? e.message : String(e) };
	} finally {
		conn?.end();
	}
}

// BUILD phase: launches the Docker build on settings.buildHost. Caller
// (launchPublish) has already checked settings.buildHost is configured.
async function launchDockerBuild(
	app: FlatpakApp,
	settings: InfraSettings,
	privateKey: string,
	paths: RemoteBuildPaths
): Promise<{ ok: boolean; log: string }> {
	const script = buildDockerBuildScript(app, settings, paths, paths.containerScriptPath);
	return launchDetachedScript(
		{ host: settings.buildHost!, user: settings.buildUser },
		privateKey,
		paths.scriptPath,
		script,
		paths.sessionName,
		paths.logPath,
		paths.exitPath,
		[{ path: paths.containerScriptPath, contents: buildContainerScript(), mode: 0o700 }]
	);
}

// PUBLISH phase: launches the sign+import+publish script on the signing
// host. localBundlePath, when set, must already exist on that host (Forge
// SFTPs it there itself before calling this - see pollBuildOnce's BUILD ->
// PUBLISH handoff) - this function only writes the script/passphrase/GPG
// key/container script. paths.containerScriptPath is the same field the
// BUILD phase already uses for its own inner script (see RemoteBuildPaths) -
// each phase mints a fresh one via remoteBuildPaths, so reusing the field
// name here never collides with the build host's.
async function launchSigningPublish(
	app: FlatpakApp,
	settings: InfraSettings,
	privateKey: string,
	gpgKey: string,
	gpgPassphrase: string,
	paths: RemoteBuildPaths,
	localBundlePath?: string
): Promise<{ ok: boolean; log: string }> {
	const script = buildRemoteScript(
		app,
		settings,
		paths.passphrasePath,
		paths.gpgKeyPath,
		paths.containerScriptPath,
		localBundlePath
	);
	return launchDetachedScript(
		signingHostTarget(settings),
		privateKey,
		paths.scriptPath,
		script,
		paths.sessionName,
		paths.logPath,
		paths.exitPath,
		[
			{ path: paths.passphrasePath, contents: gpgPassphrase, mode: 0o600 },
			{ path: paths.gpgKeyPath, contents: gpgKey, mode: 0o600 },
			{
				path: paths.containerScriptPath,
				contents: buildPublishContainerScript(app, localBundlePath),
				mode: 0o700
			}
		]
	);
}

// Builds currently being tracked by the poller below - populated by triggerPublish
// right after a successful launch, and by reconcileStuckBuilds on server startup.
const activeBuildIds = new Set<string>();

// One poll tick for one build: opens a fresh short-lived SSH connection (never
// the one that launched it), checks whether the exit-marker file exists yet,
// and either refreshes the live log (still running) or finalizes (done).
//
// Finalizing is deliberately idempotent and safe to retry: the tracked build id
// is only removed from activeBuildIds, and the remote log/exit files are only
// deleted, *after* the DB writes below actually succeed. If they throw (e.g.
// the exact transient Postgres error that originally left a row stuck on
// PROCESSING forever), this function just logs it and returns - the exit file
// is still sitting there, so the very next tick (~POLL_INTERVAL_MS later)
// re-reads it and retries the same finalize from scratch. No bespoke
// backoff/retry helper needed: a blip under one interval self-heals silently,
// a longer outage self-heals whenever Postgres comes back, and a Forge restart
// mid-outage is covered by reconcileStuckBuilds re-discovering the same build.
// Streams a file from one already-open connection straight into another's
// SFTP session, without buffering the whole thing in this process's memory -
// used for the BUILD -> PUBLISH bundle handoff below, where a real app's
// built bundle can be arbitrarily large (same "don't assume it's small"
// lesson as LOG_READ_BYTES above, just for binary data this time).
function sftpTransfer(
	fromConn: Client,
	fromPath: string,
	toConn: Client,
	toPath: string
): Promise<void> {
	return new Promise((resolve, reject) => {
		fromConn.sftp((fromErr, fromSftp) => {
			if (fromErr) return reject(fromErr);
			toConn.sftp((toErr, toSftp) => {
				if (toErr) return reject(toErr);
				const readStream = fromSftp.createReadStream(fromPath);
				const writeStream = toSftp.createWriteStream(toPath, { mode: 0o600 });
				readStream.on('error', reject);
				writeStream.on('error', reject);
				writeStream.on('close', () => resolve());
				readStream.pipe(writeStream);
			});
		});
	});
}

async function pollBuildOnce(buildId: string): Promise<void> {
	const build = await db.flatpakBuild.findUnique({
		where: { id: buildId },
		include: { flatpakApp: true }
	});
	if (!build || build.finishedAt) {
		activeBuildIds.delete(buildId);
		return;
	}

	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (!settings?.sshPrivateKeyEncrypted) return; // transient config gap, retry next tick

	const onBuildHost = build.stage === 'BUILD';
	if (onBuildHost && !settings.buildHost) return; // build host got unconfigured mid-flight, retry next tick
	const target: ConnectTarget = onBuildHost
		? { host: settings.buildHost!, user: settings.buildUser }
		: signingHostTarget(settings);

	let conn: Client | undefined;
	try {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		conn = await connect(target, privateKey);
		const sidecar = sidecarPathsFromLogPath(build.remoteLogPath);
		// The BUILD phase also has commit/metainfo/icon sidecars to read back;
		// the PUBLISH phase's script no longer produces any of those (see
		// buildRemoteScript), just a log/exit marker.
		const { output } = await execCommand(
			conn,
			`EC=""; [ -f "${build.remoteExitPath}" ] && EC=$(cat "${build.remoteExitPath}"); ` +
				`echo "$EC"; echo "${POLL_SPLIT_MARKER}"; ` +
				`tail -c ${LOG_READ_BYTES} "${build.remoteLogPath}" 2>/dev/null || true; ` +
				(onBuildHost
					? `echo "${POLL_SPLIT_MARKER}"; cat "${sidecar.commitPath}" 2>/dev/null || true; ` +
						`echo "${POLL_SPLIT_MARKER}"; cat "${sidecar.metainfoPath}" 2>/dev/null || true; ` +
						`echo "${POLL_SPLIT_MARKER}"; cat "${sidecar.iconPath}" 2>/dev/null || true`
					: '')
		);
		const parts = output.split(POLL_SPLIT_MARKER);
		if (parts.length < (onBuildHost ? 5 : 2)) return; // unexpected shape, retry next tick

		const exitCodeRaw = parts[0].trim();
		const log = parts[1].replace(/^\r?\n/, '');

		if (exitCodeRaw === '') {
			// Still running - keep the live-view log fresh, best effort only.
			await db.flatpakBuild
				.update({ where: { id: build.id }, data: { log } })
				.catch((e) => console.error(`Failed to refresh live log for build ${build.id}:`, e));
			return;
		}

		const ok = exitCodeRaw === '0';
		const app = build.flatpakApp;

		if (onBuildHost) {
			if (!ok) {
				await execCommand(
					conn,
					`rm -f "${build.remoteLogPath}" "${build.remoteExitPath}" "${sidecar.commitPath}" "${sidecar.metainfoPath}" "${sidecar.iconPath}" "${sidecar.bundlePath}"`
				).catch(() => {});
				activeBuildIds.delete(build.id);
				await finalizeLaunchFailure(build.id, app, log);
				return;
			}

			if (!settings.gpgPrivateKeyEncrypted || !settings.gpgPassphraseEncrypted) {
				await finalizeLaunchFailure(
					build.id,
					app,
					`${log}\n\n[Build succeeded, but the signing host's GPG key/passphrase is not configured - see Infra Settings.]`
				);
				return;
			}

			// The commit actually built can be later than app.gitLastCommit if more
			// pushes landed between the watcher flagging this for review and the
			// reviewer approving it - record what was really built, not just what
			// was detected. Read from its own sidecar file, not the (tail-bounded)
			// log - see BuildSidecarPaths for why a large build's own commit
			// marker can otherwise fall outside that tail.
			const gitCommit = parts[2].trim();
			const displayData = await updateDisplayDataFromSidecars(parts[3].trim(), parts[4].trim());

			const nextPaths = remoteBuildPaths(app.id);
			try {
				let signingConn: Client | undefined;
				try {
					signingConn = await connect(signingHostTarget(settings), privateKey);
					await sftpTransfer(conn, sidecar.bundlePath, signingConn, nextPaths.bundlePath);
				} finally {
					signingConn?.end();
				}
			} catch (e) {
				await finalizeLaunchFailure(
					build.id,
					app,
					`${log}\n\n[Failed to transfer the built bundle to the signing host: ${e instanceof Error ? e.message : String(e)}]`
				);
				return;
			}

			await execCommand(
				conn,
				`rm -f "${build.remoteLogPath}" "${build.remoteExitPath}" "${sidecar.commitPath}" "${sidecar.metainfoPath}" "${sidecar.iconPath}" "${sidecar.bundlePath}"`
			).catch(() => {});

			const gpgKey = decryptSecret(settings.gpgPrivateKeyEncrypted);
			const gpgPassphrase = decryptSecret(settings.gpgPassphraseEncrypted);
			const { ok: launchOk, log: launchLog } = await launchSigningPublish(
				app,
				settings,
				privateKey,
				gpgKey,
				gpgPassphrase,
				nextPaths,
				nextPaths.bundlePath
			);
			if (!launchOk) {
				await finalizeLaunchFailure(build.id, app, `${log}\n\n${launchLog}`);
				return;
			}

			try {
				await db.flatpakBuild.update({
					where: { id: build.id },
					data: {
						stage: 'PUBLISH',
						gitCommit: gitCommit || undefined,
						screenSessionName: nextPaths.sessionName,
						remoteLogPath: nextPaths.logPath,
						remoteExitPath: nextPaths.exitPath,
						log: `${log}\n\n[Build finished, handed off to the signing host to sign and publish...]`
					}
				});
				if (Object.keys(displayData).length) {
					await db.flatpakApp.update({ where: { id: app.id }, data: displayData });
				}
			} catch (e) {
				// Rare transient-DB-write case, same shape as the finalize catch
				// below - the build keeps running on the signing host regardless,
				// the next tick will retry recording this handoff. Not perfectly
				// idempotent (a second attempt would re-launch a second PUBLISH
				// script), but this is the same accepted rarity as the comment
				// on this function's finalize step already documents.
				console.error(`Failed to record BUILD -> PUBLISH handoff for build ${build.id}, will retry next tick:`, e);
				return;
			}

			return; // stays in activeBuildIds; next tick polls the PUBLISH phase
		}

		// PUBLISH phase finalize. For a GIT app this row already got its display
		// data and gitCommit applied at the BUILD -> PUBLISH handoff above; a
		// BUNDLE app never had any to begin with (see extractAppstreamMetadata).
		try {
			await db.flatpakApp.update({
				where: { id: app.id },
				data: {
					status: ok ? 'APPROVED' : 'FAILED',
					buildFinishedAt: new Date(),
					...(ok && build.gitCommit ? { gitLastCommit: build.gitCommit } : {})
				}
			});
			await db.flatpakBuild.update({
				where: { id: build.id },
				data: { status: ok ? 'SUCCESS' : 'FAILED', log, finishedAt: new Date() }
			});
		} catch (e) {
			console.error(`Failed to finalize build ${build.id}, will retry next tick:`, e);
			return;
		}

		activeBuildIds.delete(build.id);
		await execCommand(conn, `rm -f "${build.remoteLogPath}" "${build.remoteExitPath}"`).catch(() => {});

		if (app.submittedById) {
			await notifyUser(
				app.submittedById,
				ok
					? {
							type: 'flatpak_approved',
							title: `${app.name} was published`,
							link: `/dashboard/flatpaks/${app.id}`
						}
					: {
							type: 'flatpak_failed',
							title: `${app.name} failed to build`,
							body: log.slice(-500),
							link: `/dashboard/flatpaks/${app.id}`
						}
			).catch((e) => console.error(`Failed to notify submitter for build ${build.id}:`, e));
		}
	} catch (e) {
		console.error(`Poll failed for build ${buildId}, will retry next tick:`, e);
	} finally {
		conn?.end();
	}
}

let pollerStarted = false;

// Wired from hooks.server.ts next to startGitWatcher, same guard-against-double-
// start shape. Reconciliation runs once at startup so a row left on PROCESSING
// by a crash/restart (or the exact DB-write race this file's poller exists to
// survive) gets picked back up automatically instead of needing a manual retry.
export function startBuildPoller(): void {
	if (pollerStarted) return;
	pollerStarted = true;

	reconcileStuckBuilds().catch((e) => console.error('Build poller reconciliation failed:', e));

	setInterval(async () => {
		for (const buildId of [...activeBuildIds]) {
			await pollBuildOnce(buildId);
		}
	}, POLL_INTERVAL_MS);
}

async function reconcileStuckBuilds(): Promise<void> {
	const stuck = await db.flatpakApp.findMany({ where: { status: 'PROCESSING' } });
	for (const app of stuck) {
		const build = await db.flatpakBuild.findFirst({
			where: { flatpakAppId: app.id, finishedAt: null },
			orderBy: { startedAt: 'desc' }
		});
		if (build) activeBuildIds.add(build.id);
	}
}

async function finalizeLaunchFailure(buildId: string, app: FlatpakApp, log: string): Promise<void> {
	await db.flatpakApp.update({
		where: { id: app.id },
		data: { status: 'FAILED', buildFinishedAt: new Date() }
	});
	await db.flatpakBuild.update({
		where: { id: buildId },
		data: { status: 'FAILED', log, finishedAt: new Date() }
	});
	if (app.submittedById) {
		await notifyUser(app.submittedById, {
			type: 'flatpak_failed',
			title: `${app.name} failed to build`,
			body: log.slice(-500),
			link: `/dashboard/flatpaks/${app.id}`
		}).catch((e) => console.error('Failed to notify submitter of launch failure:', e));
	}
}

// Emergency stop, wired from the Infra Settings admin action: kills whatever's
// actually still running on the remote host (best effort - a session that
// already finished/never existed just no-ops) and marks every PROCESSING
// app/build FAILED. Unlike pollBuildOnce's finalize, this is a deliberate
// synchronous one-off admin action (matches repairAppstream's shape), not
// something retried automatically, so a per-app failure is recorded in the
// returned log and skipped rather than the whole call throwing.
export async function abortAllProcessingBuilds(): Promise<{
	ok: boolean;
	log: string;
	count: number;
}> {
	const apps = await db.flatpakApp.findMany({
		where: { status: 'PROCESSING' },
		include: { builds: { where: { finishedAt: null }, orderBy: { startedAt: 'desc' }, take: 1 } }
	});
	if (apps.length === 0) {
		return { ok: true, log: 'No builds are currently processing.', count: 0 };
	}

	const lines: string[] = [];
	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });

	if (settings?.sshPrivateKeyEncrypted) {
		const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);
		// A stuck build can be sitting on either host depending on its current
		// stage (see FlatpakBuildStage) - lazily open at most one connection to
		// each, reused across every app that needs that host.
		let signingConn: Client | undefined;
		let buildConn: Client | undefined;
		try {
			for (const app of apps) {
				const build = app.builds[0];
				if (!build) continue;
				const sidecar = sidecarPathsFromLogPath(build.remoteLogPath);
				try {
					if (build.stage === 'BUILD') {
						if (!settings.buildHost) {
							lines.push(`${app.appid}: build host not configured, could not abort remotely`);
							continue;
						}
						buildConn ??= await connect(
							{ host: settings.buildHost, user: settings.buildUser },
							privateKey
						);
						const { output } = await execCommand(
							buildConn,
							`screen -S "${build.screenSessionName}" -X quit >/dev/null 2>&1; ` +
								`rm -f "${build.remoteLogPath}" "${build.remoteExitPath}" "${sidecar.commitPath}" "${sidecar.metainfoPath}" "${sidecar.iconPath}" "${sidecar.bundlePath}"; echo done`
						);
						lines.push(`${app.appid}: session kill attempted on build host (${output.trim() || 'done'})`);
					} else {
						signingConn ??= await connect(signingHostTarget(settings), privateKey);
						const { output } = await execCommand(
							signingConn,
							`screen -S "${build.screenSessionName}" -X quit >/dev/null 2>&1; ` +
								`rm -f "${build.remoteLogPath}" "${build.remoteExitPath}"; echo done`
						);
						lines.push(`${app.appid}: session kill attempted (${output.trim() || 'done'})`);
					}
				} catch (e) {
					lines.push(
						`${app.appid}: could not reach its host to abort (${e instanceof Error ? e.message : String(e)})`
					);
				}
			}
		} finally {
			signingConn?.end();
			buildConn?.end();
		}
	} else {
		lines.push('Infra SSH key not configured - skipped aborting remote sessions.');
	}

	let ok = true;
	for (const app of apps) {
		const build = app.builds[0];
		try {
			if (build) {
				activeBuildIds.delete(build.id);
				await db.flatpakBuild.update({
					where: { id: build.id },
					data: {
						status: 'FAILED',
						log: `${build.log}\n\n[Aborted by an admin via Infra Settings.]`,
						finishedAt: new Date()
					}
				});
			}
			await db.flatpakApp.update({
				where: { id: app.id },
				data: { status: 'FAILED', buildFinishedAt: new Date() }
			});
			if (app.submittedById) {
				await notifyUser(app.submittedById, {
					type: 'flatpak_failed',
					title: `${app.name} failed to build`,
					body: 'The build was aborted by an administrator.',
					link: `/dashboard/flatpaks/${app.id}`
				}).catch((e) =>
					console.error(`Failed to notify submitter for aborted build ${app.id}:`, e)
				);
			}
			lines.push(`${app.appid}: marked FAILED`);
		} catch (e) {
			ok = false;
			lines.push(`${app.appid}: failed to update - ${e instanceof Error ? e.message : String(e)}`);
		}
	}

	return { ok, log: lines.join('\n'), count: apps.length };
}

const triggeringApps = new Set<string>();

// Creates the FlatpakBuild history row, prunes anything past the 10 most recent
// for this app, then launches the build detached (see launchDockerBuild /
// launchSigningPublish) and hands it off to the shared poller. Doesn't await
// the build itself completing -
// the caller (the review approve/retry action) returns immediately, same as
// before, but the build's outcome is now tracked durably instead of living only
// in this async call's own stack.
export function triggerPublish(flatpakAppId: string, triggeredById?: string): void {
	if (triggeringApps.has(flatpakAppId)) return;
	triggeringApps.add(flatpakAppId);
	launchPublish(flatpakAppId, triggeredById).finally(() => triggeringApps.delete(flatpakAppId));
}

async function launchPublish(flatpakAppId: string, triggeredById?: string): Promise<void> {
	const app = await db.flatpakApp.findUnique({ where: { id: flatpakAppId } });
	if (!app) return;

	const paths = remoteBuildPaths(app.id);
	// GIT submissions start on the Docker build host (no secrets involved);
	// BUNDLE submissions skip straight to the signing host, same as before.
	const stage: 'BUILD' | 'PUBLISH' = app.sourceType === 'GIT' ? 'BUILD' : 'PUBLISH';
	const build = await db.flatpakBuild.create({
		data: {
			flatpakAppId: app.id,
			status: 'PROCESSING',
			log: '',
			stage,
			screenSessionName: paths.sessionName,
			remoteLogPath: paths.logPath,
			remoteExitPath: paths.exitPath,
			triggeredById
		}
	});

	const stale = await db.flatpakBuild.findMany({
		where: { flatpakAppId: app.id },
		orderBy: { startedAt: 'desc' },
		skip: 10,
		select: { id: true }
	});
	if (stale.length) {
		await db.flatpakBuild.deleteMany({ where: { id: { in: stale.map((b) => b.id) } } });
	}

	const settings = await db.infraSettings.findUnique({ where: { id: 'singleton' } });
	if (!settings) {
		await finalizeLaunchFailure(build.id, app, 'Infra settings are not configured.');
		return;
	}
	if (!settings.sshPrivateKeyEncrypted) {
		await finalizeLaunchFailure(
			build.id,
			app,
			'Infra settings are not fully configured (missing SSH key).'
		);
		return;
	}
	const privateKey = decryptSecret(settings.sshPrivateKeyEncrypted);

	if (stage === 'BUILD') {
		if (!settings.buildHost) {
			await finalizeLaunchFailure(
				build.id,
				app,
				'No Docker build host is configured (Infra Settings - Build Host) - GIT-sourced Flatpaks cannot be built.'
			);
			return;
		}
		const { ok, log } = await launchDockerBuild(app, settings, privateKey, paths);
		if (!ok) {
			await finalizeLaunchFailure(build.id, app, log);
			return;
		}
	} else {
		if (!settings.gpgPrivateKeyEncrypted || !settings.gpgPassphraseEncrypted) {
			await finalizeLaunchFailure(
				build.id,
				app,
				'Infra settings are not fully configured (missing GPG key or GPG passphrase).'
			);
			return;
		}
		const gpgKey = decryptSecret(settings.gpgPrivateKeyEncrypted);
		const gpgPassphrase = decryptSecret(settings.gpgPassphraseEncrypted);
		const { ok, log } = await launchSigningPublish(app, settings, privateKey, gpgKey, gpgPassphrase, paths);
		if (!ok) {
			await finalizeLaunchFailure(build.id, app, log);
			return;
		}
	}

	activeBuildIds.add(build.id);
}
